### ISSUE TITLE
Unknown mod/mods causing issues with Event#setCanceled()

### ISSUE THREAD

**Issue by DeLoreanPro** [MrJake222/AUNIS#102]
If the player has the Thermal family of mods; Thermal expansion, dynamics, foundation, Universe gates (U) will fail to connect to other Universe gates and when doing a 9 chevron dial with a Milky Way (MW) gate, trying to click glyph 8 causes a game crash to desktop.

**Comment by MrJake222** [comment]
[crash-2020-04-04_19.52.08-client.txt](https://github.com/MrJake222/AUNIS/files/4433922/crash-2020-04-04_19.52.08-client.txt)
* First, this crash log(Assuming it's yours) indicates more mod present than just Thermal series.
* Second, I wasn't able to reproduce the crash with these mods:
![Screenshot_20200405_161801](https://user-images.githubusercontent.com/7581790/78500830-0b15e380-7759-11ea-98e3-cf6519aaea8a.png)

**Comment by MrJake222** [comment]
Oh and I have Forge 14.23.5.2847, you seem to have an older version.

**Comment by MrJake222** [comment]
If someone will reproduce it(with minimal mods) on **1.9.1**, please provide info. I "fixed" that with some walkaround...

**Comment by craft90** [comment]
Ran into the same crash.
Here's the crash log: https://pastebin.com/ax0r2qeP

**Comment by MrJake222** [comment]
Can you eliminate mods one by one to see which one is causing issues?

**Comment by craft90** [comment]
Well after removing basically every mod I've come to the conclusion that it's not a mod conflict. It's a bug in AUNIS itself. It appears when you try to dial when the Cold Fusion generator is running but the buffer of the gate isn't filled. This is also on the 1.9.1-beta version.

**Comment by craft90** [comment]
Well after removing basically every mod I've come to the conclusion that it's not a mod conflict. It's a bug in AUNIS itself. It appears when you try to dial but somehow miss click the symbols. Either hitting to close to the red button, standing too far away and clicking etc. It appears to be random. Standing close to the DHD and aiming well doesn't cause the issue.
