### ISSUE TITLE
Server keeps crashing on start up with 1.9/1.9+ Version

### ISSUE THREAD

**Issue by wasabi2016** [MrJake222/AUNIS#105]
I tried to set up a Server with AUNIS Mod Version 1.9/1.9+ but it keeps crashing on start up. 
[latest.log](https://github.com/MrJake222/AUNIS/files/4434825/latest.log)
[latest (Mod Version 1.9.1-beta.log](https://github.com/MrJake222/AUNIS/files/4434832/latest.Mod.Version.1.9.1-beta.log)

**Comment by RedstoneSucht** [comment]
Server crash confirmed. We have the same problem.
(Dialer Item)

**Comment by kaiserdj** [comment]
Same crash server
[crash-2020-04-06_19.38.56-server.txt](https://github.com/MrJake222/AUNIS/files/4439958/crash-2020-04-06_19.38.56-server.txt)

**Comment by uncoveredkhan09** [comment]
any idea when this is going to be fixed? no real pressure but i really want to use the universe gates ;-;
