### ISSUE TITLE
OC point of origin issue

### ISSUE THREAD

**Issue by PoltixeTheDerg** [MrJake222/AUNIS#107]
with the latest update, if you do not have enough power and you try to engage the point of origin in OC, it says "stargate_spin", which shows that it worked, but the gate itself sounds the locking, nothing visual happens, then the gate returns to an idle state

**Comment by MrJake222** [comment]
I think getting `stargateSpin` is not the issue here. You're saying that's spinning to the symbol and then trying to lock it and failing? If so the gate should send a reason of the failure with `stargateFailed` signal. Correct me If I'm wrong.

**Comment by PoltixeTheDerg** [comment]
yes you're correct
