### ISSUE TITLE
Universe gates and "Stargate size" config option

### ISSUE THREAD

**Issue by Geocube101** [MrJake222/AUNIS#108]
*Not sure if this is planned*
My stargate size in the mod options is still set to large (because I liked the large stargate size) but the universe gate still uses the small or medium (not sure which) size when you place the base block.
Can the universe gates respect the stargate size option?

**Comment by MrJake222** [comment]
Look, keeping the 2 variants of Milky Way was already a mistake. Now I have to keep 2 variants of each structure, update 2 variants of each structure...

**Comment by Geocube101** [comment]
I see your point.
