### ISSUE TITLE
Stargate can dial itself

### ISSUE THREAD

**Issue by Firecreeper240** [MrJake222/AUNIS#11]
It is possible to dial a Stargate to iteself.  Doing this prevents you from closing it, requiring you to break the Stargate and DHD. Also, it would be more realistic to block a Stargate from dialing itself.

**Comment by engineeringuofi** [comment]
That might have been with the can't walk through Stargate/gate won't close issue

**Comment by MrJake222** [comment]
This *should not* be possible... I have checks for that. I'll look into 
that tomorrow.

Sent with AquaMail for Android
https://www.mobisystems.com/aqua-mail
