### ISSUE TITLE
Addition of OC command to get gate type

### ISSUE THREAD

**Issue by Geocube101** [MrJake222/AUNIS#112]
My dialing program was designed for the milky way gates but I wanted the ability to automatically detect which gate the computer was connected to. If it's not too much to ask, maybe there could be an OC command ("getGateType"?) that returns the type of gate as a string.

*Example:*
local sg = require("component").stargate
local type = sg.getGateType()
--Could return "milky_way", "pegasus", or "universe"

If it is too much to ask then I'm sure i can find a way to manually test for the gate's type

**Comment by MrJake222** [comment]
It's the easiest thing to do. Thanks for the suggestion.
