### ISSUE TITLE
attempt to dial a random incomplete set of gates and cause

### ISSUE THREAD

**Issue by KiraLinux** [MrJake222/AUNIS#114]
All information about mods and versions is in these files.
and the problem that I had

I built the gates, put the gates call panel, filed refined naquadah and tried to press absolutely any keys and call, but the game crashed

[latest.log](https://github.com/MrJake222/AUNIS/files/4443989/latest.log)
[crash-2020-04-07_14.46.16-client.txt](https://github.com/MrJake222/AUNIS/files/4443992/crash-2020-04-07_14.46.16-client.txt)

**Comment by MrJake222** [comment]
Related to #102. Try limiting the mod list to minimum required and post your results there.
