### ISSUE TITLE
Phantom Gate

### ISSUE THREAD

**Issue by darkwolf-x2** [MrJake222/AUNIS#115]
You can go through gate that are not formed.

Put two base block, power the first, get the address from the second one, dial it. You'll hear the sound, but no visual, apart from the kawoosh destroying blocks particles.

**Comment by MrJake222** [comment]
How can you dial a unmerged base block? With DHD, OC? Or only the receiving gate is not merged?

**Comment by darkwolf-x2** [comment]
That's what I'm asking myself... 

I've put the base block, then the DHD. Put the control crystal inside and it linked up to the gate, although it's not merged. Both of the gate are not merged. Added power, then dialed. Like that it's fine and connect, but not to a mysterious gate. If you try that it will crashed with the event canceler. 

You can even build the gate to merge it and it will look active and everything. Put if you break a block, the bug won't work. If you break the DHD and replace it, etc. then the bug will reappear.
