### ISSUE TITLE
Add a KINO

### ISSUE THREAD

**Issue by StargateDestiny** [MrJake222/AUNIS#120]
I want kino in this mod, its really awesome if I generated random gate, open it and send kino to see what around this gate.

**Comment by PoltixeTheDerg** [comment]
would not be possible (or near impossible) to implement, you can't load and view chunks that aren't in your render distance so it would not work for that

**Comment by MrJake222** [comment]
@PoltixeTheDerg is right. The gate rendering is sketchy and it likes to disappear. It's not GMod's CAP 1:1 clone

**Comment by uncoveredkhan09** [comment]
security craft did it with cameras tho
