### ISSUE TITLE
Add craft to universe dialer

### ISSUE THREAD

**Issue by StargateDestiny** [MrJake222/AUNIS#121]
We need craft of universe dialer,  its Hard to find, and if we Dont have universe dialer, we cant dial universe stargate.

**Comment by PoltixeTheDerg** [comment]
Jake already said no crafting recipe will exist, the entire point of the dialer is to be rare

**Comment by MrJake222** [comment]
And you can always use OC... The Universe gate is cheaper, but to use it early-game you need to either rush End or use OC. I'm sure you can find your way with craft tweaker or something.
