### ISSUE TITLE
[OpenComputer Integration] cannot remove engaged chevrons

### ISSUE THREAD

**Issue by Nex4rius** [MrJake222/AUNIS#125]
If the stargate has some chevrons engaged then disengageGate() does nothing.

There is a workaround with using engageGate() to reset the gate but that only works as long as the engaged chevrons is less than 7.

**Comment by PoltixeTheDerg** [comment]
`disengageGate()` is for disengaging an already open gate, and they couldn't in the show so I don't see a need.

**Comment by Nex4rius** [comment]
I'm pretty sure they could interupt a dialling sequence (and the chevrons turned off).

**Comment by PoltixeTheDerg** [comment]
yes they could interrupt, and you can recreate by engaging the gate

**Comment by Nex4rius** [comment]
Okay its just "weird"

**Comment by PoltixeTheDerg** [comment]
well why have another function when one already exists

**Comment by Nex4rius** [comment]
It's just that we have an interupted dialling sequence and we want to "disengage" it.
There are 2 function in the computer:
disengageGate()
engageGate()

Which one would "disengage" the gate and make it ready for a new dialling ;P?

**Comment by PoltixeTheDerg** [comment]
disengaging the gate is referring to when its open, and engageGate() gives more info so its a better option anyway

**Comment by Nex4rius** [comment]
Sure keep it that way but it's a bit silly now because my function to close it will be something like this now:

```lua
function close()
  if not sg.disengageGate() then
    sg.engageGate()
  end
end
```

**Comment by PoltixeTheDerg** [comment]
disengageGate() doesn't work like that

**Comment by PoltixeTheDerg** [comment]
closing the gate is just sg.disengageGate()
clearing chevrons is sg.engageGate()
