### ISSUE TITLE
[OpenComputer Integration] missing stargate functions

### ISSUE THREAD

**Issue by Nex4rius** [MrJake222/AUNIS#126]
The <a href="https://github.com/MrJake222/AUNIS/wiki/OpenComputers-integration">wiki</a> has like a lot of functions for the stargate but the computer only sees 3 function in the game.

The computer sees those:
disengageGate()
engageGate()
engageSymbol()

but those are missing:
getGateType()
getEnergyStored()
getMaxEnergyStored()
getCapacitorsInstalled()

**Comment by PoltixeTheDerg** [comment]
you are probably running an old version of the mod

**Comment by Nex4rius** [comment]
Sure I'll check that ...
<img src="https://i.imgur.com/o9W2glQ.png">
And in my minecraft folder... a newer version wtf?
<img src="https://imgur.com/dCWqOAM.png">

**Comment by PoltixeTheDerg** [comment]
uh the release on the github was a very early 1.9 test version
also 1.9.3 is the latest

**Comment by PoltixeTheDerg** [comment]
https://www.curseforge.com/minecraft/mc-mods/aunis/files
download the latest version here ^^^^

**Comment by Nex4rius** [comment]
thanks :)
