### ISSUE TITLE
Mob Pathfinding Issue

### ISSUE THREAD

**Issue by brom10** [MrJake222/AUNIS#131]
When other mobs travel through a gate between dimensions, they are unable to pathfind. Relogging fixes this

**Comment by MrJake222** [comment]
I've tried to replicate this with the Nether->Overworld travel and the other way around with spiders. They could find me easily. Any specific details?

**Comment by MrJake222** [comment]
Uhhh I was trying with spiders because they don't burn up in the sun xD
