### ISSUE TITLE
new signal for gate

### ISSUE THREAD

**Issue by PoltixeTheDerg** [MrJake222/AUNIS#138]
a signal coming from the gate every time a new glyph is at the top of the gate, so its possible to display what glyph is currently at the top of the gate on an OC

**Comment by MrJake222** [comment]
Best I can do is when the ring stops at certain symbol. The actual ring's rotation only happens client sidem

**Comment by PoltixeTheDerg** [comment]
huh, I thought they were server-side as the animation speed seemed to be about the same as the game tick-rate
