### ISSUE TITLE
Nothing happens when i go through a gate + crash

### ISSUE THREAD

**Issue by KyroOW** [MrJake222/AUNIS#14]
I made two gates, powered both gates and DHD, everything seems to work, except when i try to go through the gates nothing happens at all, i get nothing in the console either.

so i tried to push a pig in a gate and then the server crashed instantly
[crash-2019-07-12_20.32.51-server.txt](https://github.com/MrJake222/AUNIS/files/3387717/crash-2019-07-12_20.32.51-server.txt)

edit: works fine in single player though, pushing pig in gate works fine too

**Comment by MrJake222** [comment]
WHAT. THE. FUCK.

Why there is no class "org.lwjgl.util.vector.Matrix2f"... The coremods are fucking something over...

> edit: works fine in single player though, pushing pig in gate works fine too

With the same modpack?

**Comment by KyroOW** [comment]
Yes, it's the same, server side i only deleted the client side only mods, like optifine for example, everything else is the same, including the configs (i didn't touched aunis config though)

only change is that the server is running sponge

**Comment by MrJake222** [comment]
I see Sponge on the stacktrace:
> at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:237)

I suspect that's the reason... But I don't get why is Sponge removing classes. I might bundle the class into AUNIS(checked, license allows it).

**Comment by MrJake222** [comment]
#17. Not sponge's fault. Closing this one.
