### ISSUE TITLE
Wormhole_stabilized signal

### ISSUE THREAD

**Issue by Nex4rius** [MrJake222/AUNIS#140]
It would be really cool if the wireless singals from the computer could go through an open wormhole.
Or possibly easier to implement a way with the computer to send a singal to a computer attached to the stargate at the other side.

**Comment by MrJake222** [comment]
Isn't that a thing already? Have you tested it?

**Comment by PoltixeTheDerg** [comment]
I think it should be added to the wiki, to stop future confusion.

**Comment by MrJake222** [comment]
@MR-Spagetty

**Comment by Nex4rius** [comment]
1) It's not in the wiki ^^

2) I used the stargate_open event and then startet sending but the first wirless signals can only go through ~3 seconds after this event.

Could you delay the event or add another "wormhole_stabilized" or something?

**Comment by MrJake222** [comment]
Will do

**Comment by Nex4rius** [comment]
Thanks :)

**Comment by MR-Spagetty** [comment]
so what exactly is it that I need to add to the wiki?

**Comment by PoltixeTheDerg** [comment]
Wireless messages @MR-Spagetty

**Comment by MR-Spagetty** [comment]
yes yes I know that mich but I need to know what toh need to have in your code and what said function does

**Comment by MrJake222** [comment]
Only add the info that Stargates are capable of retransmitting OC messages through the open wormhole. Probably on the Stargate (General).
