### ISSUE TITLE
Pegasus glyph asthetic issue

### ISSUE THREAD

**Issue by PoltixeTheDerg** [MrJake222/AUNIS#141]
I think most people agree that the new pegasus glyphs don't look very good, they seem to be a bit off from the clean aesthetic of the other glyph types.
new one:
![aaxel](https://user-images.githubusercontent.com/34501060/79678596-184bbd00-81b2-11ea-811f-fe554ddca82d.png)
old one:
![aaxel](https://user-images.githubusercontent.com/34501060/79678605-2699d900-81b2-11ea-8d5b-4a32490d2a22.png)
MW:
![virgo](https://user-images.githubusercontent.com/34501060/79678611-2f8aaa80-81b2-11ea-83bc-bd984f2f9fde.png)
UN:
![g15](https://user-images.githubusercontent.com/34501060/79678612-331e3180-81b2-11ea-86d4-3388bef057b1.png)
as is very obvious it does not fit

or in augurs words "they look like fried chicken fingers stuck together"

**Comment by MrJake222** [comment]
But the DHD ones look like this, and seriously, you don't want to match them real-time xD

**Comment by MrJake222** [comment]
![Screenshot_20200419-093407675 (1)](https://user-images.githubusercontent.com/7581790/79682262-f9384400-8220-11ea-8363-ddc2892c9186.jpg)

**Comment by PoltixeTheDerg** [comment]
Well, it's possible to make it better without completely bombing the aesthetic of the glyphs, perhaps making the lines between each dot on the glyphs the width of the dots themselves? so it looks a bit closer to the smoothness of the other glyph types.

**Comment by MrJake222** [comment]
Then go and make one... It's just CAP's texture.
