### ISSUE TITLE
Universe Gate Bug, when Dial too fast

### ISSUE THREAD

**Issue by KamaroTheN7** [MrJake222/AUNIS#150]
Easy to reproduce, but It mostly will affect multiplayer, to resolve issue with dialing gate you can just reload world, but with dialed you must destroy baseblock, when tried to dial it, gate will appear as busy. Here a video: [https://youtu.be/Oe4DXeY-kEI](url)
Sorry for my English, I'm not a native speaker, you mod is awesome!
mod version 1.9.6

**Comment by MrJake222** [comment]
What are the steps to reproduce exactly?

**Comment by KamaroTheN7** [comment]
Its showed in video, but I can write it if you wish. When gate disengage wormhole, chevrons and glyphs stop glowing immediately right click with dialer to start dial another address, when it finish gate will hve wormhole without engaged glyphs or chevrons, it will fix itself after reloading world, but gate that revived connection will stay bugged until you don't break and put base black again.

**Comment by ShicKla** [comment]
@MrJake222 I was also able to duplicate. The problem seems to be that the gate is trying to reset it's angle back to its resting position and the same time it is also trying to change its angle to dial the address.

**Comment by KamaroTheN7** [comment]
> 
> 
> @MrJake222 I was also able to duplicate. The problem seems to be that the gate is trying to reset it's angle back to its resting position and the same time it is also trying to change its angle to dial the address.

I think that same, code that reset it position still work and its probably overwritten by dialing code. Anyway I checked is there any other way to fix (in game) but gate that revived bugged connection will stay in that way until breaking the base block, the gate that was dialing how ever can be fix without reload of the world, you can simply dial another gate.

**Comment by KamaroTheN7** [comment]
`you can simply dial another gate` And apparently dial to that gate (with not lighted up chevrons and glyphs) from Milky way type, from another Universe type gate it will act like busy.

**Comment by KamaroTheN7** [comment]
When universe gate disengage wormhole and gate is spinning to return to starting point and when it spin this gate have incoming wormhole chevrons will not light up, fortunately, that's only visual bug, related to main bug of this thread.

**Comment by MrJake222** [comment]
Okay blocked it xD
