### ISSUE TITLE
Lack of top texture of chevrons in SGU gate type model from front site.

### ISSUE THREAD

**Issue by KamaroTheN7** [MrJake222/AUNIS#152]
![Minecraft 1 12 2 24 04 2020 16_46_13](https://user-images.githubusercontent.com/55023705/80233981-a5ca5980-8657-11ea-8cef-533391d6f464.png)
![Minecraft 1 12 2 24 04 2020 16_46_31](https://user-images.githubusercontent.com/55023705/80233983-a7941d00-8657-11ea-9ee4-0e45e48b00e0.png)

**Comment by MrJake222** [comment]
![Screenshot_20200424-194931023 (1)](https://user-images.githubusercontent.com/7581790/80241927-c51bb380-8664-11ea-9cc9-6117e64b2a2a.jpg)
What texture? They didn't have any...

**Comment by KamaroTheN7** [comment]
![InkedMinecraft 1 12 2 24 04 2020 16_46_31_LI](https://user-images.githubusercontent.com/55023705/80251604-2bf59880-8676-11ea-9e8b-8557353a6732.jpg)
If you gonna take closer look on red (gate front site) marked you can see that little rectangle is missing. On it counter blu site (gate back site) it is there./Jeżeli przypatrzeć się bliżej, to widać, że brakuje fragmentu modelu zasłaniającego grzbiet chevronu, podczas, gdy patrzeć na chevrony po stronie wrót bez glifów można dostrzec, że jest mały wydłużony prostokąt, którego nie ma po stronie z glifami.

**Comment by KamaroTheN7** [comment]
tu zamalowałem brakujący i jego odpowiednik po drugiej stronie, który jest, zamiast tylko w obódkę wziąć. 
![Inked2Minecraft 1 12 2 24 04 2020 16_46_31_LI](https://user-images.githubusercontent.com/55023705/80252583-d1f5d280-8677-11ea-9a73-e662ba7016a7.jpg)

**Comment by MrJake222** [comment]
Zobaczę potem w grze może wtedy ogarnę xD
