### ISSUE TITLE
Same craft

### ISSUE THREAD

**Issue by MarcCrams** [MrJake222/AUNIS#155]
Hello, I have a problem to craft DHD Glyph Crystal because DHD Glyph Crystal and Beamer Items Crystal have the same craft. So when I  want to craft a DHD Glyph Crystal I craft a Beamer Items Crystal.

**Comment by KamaroTheN7** [comment]
Yes, indeed we have a problem, XD I would just fix it, with instead horizontal, for beamer it would be vertical.

**Comment by MrJake222** [comment]
Shit... not again xD

**Comment by MrJake222** [comment]
Nice idea @KamaroTheN7
