### ISSUE TITLE
Milky Way Type Gate lack of texture.

### ISSUE THREAD

**Issue by KamaroTheN7** [MrJake222/AUNIS#157]
backside of Chevron 5 (or 8 if you counting from max top, clockwise) have a lack of texture.
![2020-04-25_18 24 20](https://user-images.githubusercontent.com/55023705/80285154-45a0e980-8723-11ea-9244-94f01764dec5.png)
![2020-04-25_18 26 14](https://user-images.githubusercontent.com/55023705/80285157-476aad00-8723-11ea-8584-83ec360a4dcf.png)

**Comment by PoltixeTheDerg** [comment]
happens with chevron 6 too
![javaw_INB5EU0ThM](https://user-images.githubusercontent.com/34501060/80290496-28a3f080-86fa-11ea-90cf-6f2ec7edf2c8.png)
