### ISSUE TITLE
Bug: OC Integration getEnergyRequiredToDial() function error with LUA 5.3

### ISSUE THREAD

**Issue by ShicKla** [MrJake222/AUNIS#162]
When using LUA 5.3, and you pass a table of an address to the `getEnergyRequiredToDial()` function it will return nil with the error message `invalid key to 'next'`

**Comment by MrJake222** [comment]
It's not Aunis issue. OC is fucking up somewhere. I've created issue in their repo
https://github.com/MightyPirates/OpenComputers/issues/3282
Gonna see what happens...

**Comment by MrJake222** [comment]
But you can always use `table.unpack`
![Screenshot_20200426_121155](https://user-images.githubusercontent.com/7581790/80304563-2a7fb980-87b7-11ea-9fe2-ca198e482775.png)

**Comment by ShicKla** [comment]
Stupid OC.... Oh well what can we do. Funny your suggestion is what I ended up already doing
