### ISSUE TITLE
Gates power

### ISSUE THREAD

**Issue by Powergate1** [MrJake222/AUNIS#163]
When connected to a energy source even when the power banks are full and a wormhole is not active it continues to draw power from my reactor

**Comment by MrJake222** [comment]
I'm unable to replicate your issue. I used Thermal Expansion fluxducts and Aunis's Capacitor Bank. And I was using Milky Way gate. Please give some more details about your setup and make sure you're on the latest version of the mod.

**Comment by weberlepecheur** [comment]
If i'm guessing correctly, the stargate have 25% energy buffer, the 3 capacitors up to 100% the buffer (25% per capacitor). So even if your capacitor are full, if the stargate isn't it will continue to draw until 100%.

Or are you talking about when your energy buffer is at 100% ?

**Comment by MrJake222** [comment]
No further input from the OP, closing.
