### ISSUE TITLE
dialing from universe gate to milkyway gate impossible

### ISSUE THREAD

**Issue by Nex4rius** [MrJake222/AUNIS#166]
https://youtu.be/qW-aYwja354

It works fine from universe to universe stargate.

**Comment by KamaroTheN7** [comment]
I can dial without any problems: https://youtu.be/-CC3JOspbAM

**Comment by KamaroTheN7** [comment]
I love you dialing program for OC, btw.

**Comment by Nex4rius** [comment]
@KamaroTheN7  thanks :)

That's strange.
I have aunis-1.12.2-1.9.6-beta installed and you?

**Comment by KamaroTheN7** [comment]
I tested that dialing with 1.9.5 & 1.9.6 & 1.9.7

**Comment by KamaroTheN7** [comment]
I noticed that instead Glyph 17 you use "Point of Origin", I did that same mistake, than I look at my universe dialer and from counting regualr address it was 7, and last was always that same glyph, so I matched it on Stargate Command wiki, and it was Glyph 17, I think "Point of Origin" is only for MW Gates and will be used in Pegasus one too, for universe gate point of orgin is Glyph 17.

**Comment by KamaroTheN7** [comment]
I also noticed that you was using regular 6 (+ POO) to dial milky way gate with ancient handheld dialer, you must first insert SGU glyph crystal and Stargate glyph upgrade crystal, than but dialer in SGU glyph slot, after that you will have 8 Glyph address of that milky way gate in ancient handheld dialer, switch from "Nearby" to "Memory", than dial. (to switch between modes of work hold "Ctrl" and scroll you mouse)

**Comment by PoltixeTheDerg** [comment]
Dialing from universe to milkyway and back requires 9 chevrons, and the point of origin is 17.

**Comment by Nex4rius** [comment]
That is interesting.
Why is that different with universe gates?

**Comment by PoltixeTheDerg** [comment]
it is different because they are referenced by numbers not names, and having one referenced by a name would ruin that cohesion
