### ISSUE TITLE
stargate stuck

### ISSUE THREAD

**Issue by Nex4rius** [MrJake222/AUNIS#169]
I don't know how I did that but it happend to both gates at the same time.
aunis-1.12.2-1.9.6-beta

https://youtu.be/kbtpNEu0FgQ

**Comment by KamaroTheN7** [comment]
It was fixed (or part of it). It would be the best if you would use the mos current version, than report a bug. #150

**Comment by KamaroTheN7** [comment]
We still don't know how you get stuck milky way type gate...

**Comment by Nex4rius** [comment]
Okay... but as I said I don't know how it happend.

**Comment by Nex4rius** [comment]
It happend again but no idea how with the newest version 1.9.7.

**Comment by Nex4rius** [comment]
I figuered it out: https://youtu.be/-4qvkJOBYAY

**Comment by PoltixeTheDerg** [comment]
Ah so it is related to #150, this is just the OC version of the bug

**Comment by MrJake222** [comment]
![Screenshot_20200512_185504](https://user-images.githubusercontent.com/7581790/81722734-1cea5500-9482-11ea-878e-53a9b608e998.png)
I wasn't able to do this for example. Can you give me the commands you're calling to get this bug?

**Comment by Nex4rius** [comment]
Are you sure you didn't fix it already? I can't reproduce it anymore.

**Comment by MrJake222** [comment]
Maybe i fixed it with #150 as Poltixe pointed out it was related. Anyway glad it's fixed ;)
