### ISSUE TITLE
Beamers didn't work between dimensions

### ISSUE THREAD

**Issue by MarcCrams** [MrJake222/AUNIS#171]
Since the last update I can't connect beamers between dimensions.

**Comment by MrJake222** [comment]
You sure you've placed them in the right spot? Can you connect them in the same dimension?

**Comment by MarcCrams** [comment]
Yes and yes

**Comment by ShicKla** [comment]
@MrJake222 could it be that the chunk that one of the beamers is in, has become unloaded?
