### ISSUE TITLE
opencomputer cant find stargate

### ISSUE THREAD

**Issue by Nex4rius** [MrJake222/AUNIS#173]
It happens sometimes that the computer cannot find the stargate anymore until you break the stargate base block or reload the save.

<img src="https://imgur.com/82oD8hO.png">
<img src="https://imgur.com/dt7Hu8L.png">
<img src="https://imgur.com/H6al6kD.png">

**Comment by PoltixeTheDerg** [comment]
So it'll work just fine and then just disappear?

**Comment by Nex4rius** [comment]
Yes. It only happend twice so far.

**Comment by ShicKla** [comment]
Prior to the stargate component not showing, did the computer turn itself off for no reason?

**Comment by Nex4rius** [comment]
Yes it was off.

**Comment by PoltixeTheDerg** [comment]
huh then I've also dealt with this bug then, it seems to be when the chunks the gate and computer are in become unloaded

**Comment by Nex4rius** [comment]
Sadly it happens way more frequent,

I've tested it now.
5 stargate with a computer in the overworld.
I went to the nether via the stargate and came back.

2 stargates didnt show up on the computer anymore.

https://youtu.be/Y3iEccBzG-4

aunis-1.12.2-1.9.7-beta

**Comment by MrJake222** [comment]
`latest.log`?

**Comment by Nex4rius** [comment]
[debug.log](https://github.com/MrJake222/AUNIS/files/4615451/debug.log)
[latest.log](https://github.com/MrJake222/AUNIS/files/4615453/latest.log)

**Comment by MrJake222** [comment]
Okay I've managed to reproduce it.

> [16:48:06] [Server thread/WARN] [opencomputers]: A component of type 'stargate' disappeared (fc097851-f632-40a5-ae73-cc64dc7ed9bf)! This usually means that it didn't save its node.

**Comment by MrJake222** [comment]
Okay I fixed this one. But one issue still bugs me. Did you notice the computer turning off when you return to the Overworld from the Nether for example?

**Comment by Nex4rius** [comment]
Yes sometimes the computer were off.
