### ISSUE TITLE
animated event horizon

### ISSUE THREAD

**Issue by Nex4rius** [MrJake222/AUNIS#178]
It would be super cool if you could animate the event horizon texture.

For example :)
<img src="https://thumbs.gfycat.com/InexperiencedUnconsciousIrishwaterspaniel-size_restricted.gif">

**Comment by MrJake222** [comment]
Do you have some perfect loop videos of the horizon?

**Comment by Nex4rius** [comment]
<a href="https://youtu.be/44gxlwMMEUo">Sure.</a>

[loop.zip](https://github.com/MrJake222/AUNIS/files/4606869/loop.zip)

**Comment by Nex4rius** [comment]
<a href="https://youtu.be/436Ut0UwNSA">Universe is sadly worse quality.</a>

[sgu loop.zip](https://github.com/MrJake222/AUNIS/files/4606895/sgu.loop.zip)

**Comment by MrJake222** [comment]
![Screenshot_20200513_202341](https://user-images.githubusercontent.com/7581790/81850012-a91a7c00-9557-11ea-86ef-3f17c602b24e.png)
*Reasonable...*

**Comment by Nex4rius** [comment]
Aunis 30MB + both loops 10 MB = 40MB? How did you get it to 164MiB?

**Comment by MrJake222** [comment]
Extracted single frames into PNGs. JPEGs are 15MB at 50% quality but the compression eats a lot of quality

**Comment by MrJake222** [comment]
And a loading time is horrible. It lags as hell for the first minute or so

**Comment by Nex4rius** [comment]
I mean you could reduce quality. I doesn't have to be 60fps 4k xD

**Comment by Nex4rius** [comment]
I extracted all frames at 20fps and I get a totaly size of 12MB.
[frames.zip](https://github.com/MrJake222/AUNIS/files/4624573/frames.zip)

**Comment by MrJake222** [comment]
I'm working on it and reporting live on Discord xD Btw come join us :p

**Comment by Nex4rius** [comment]
sure I just need the discord link :)

**Comment by MrJake222** [comment]
https://discord.gg/7S2nRe7

**Comment by Nex4rius** [comment]
Invalid invite link :(

**Comment by MrJake222** [comment]
https://discord.gg/T9zFcY

**Comment by Nex4rius** [comment]
AWESOME
