### ISSUE TITLE
Hi, do anybody know what that means?

### ISSUE THREAD

**Issue by MikiCZSK** [MrJake222/AUNIS#182]
Error from Open coputer can be seen here:
![error](https://user-images.githubusercontent.com/65219648/81821745-84f87400-9532-11ea-8991-9f4c73208267.png)

**Comment by MrJake222** [comment]
You don't have a stargate connected to your computer

**Comment by MikiCZSK** [comment]
I have, in left side of the picture is interface

**Comment by MikiCZSK** [comment]
It was just some bug with opencomputers. I disassembled gate and reassembled and it now works
