### ISSUE TITLE
Overwriting mysterious pages

### ISSUE THREAD

**Issue by Geocube101** [MrJake222/AUNIS#185]
Not sure if this was supposed to happen but I used the mysterious page to generate a gate and then placed the page into a glyph slot in my home stargate. The gate then overwrote the symbols on the page and as such i have no idea were the mysterious gate is.

**Comment by MrJake222** [comment]
You can reuse pages. Imagine you've changed your gate location and then what? Sadly, overwriting a Mysterious Page was stupid and only way to get it's address is by using `/sgquery` now.
