### ISSUE TITLE
aunis is not working on private servers scince 1.8.9

### ISSUE THREAD

**Issue by anzestrela** [MrJake222/AUNIS#187]
it just crashes log:
[latest.log](https://github.com/MrJake222/AUNIS/files/4639339/latest.log)

**Comment by wasabi2016** [comment]
Same Problem with the new Version , here is my Log File
[2020-05-16-5.log](https://github.com/MrJake222/AUNIS/files/4639493/2020-05-16-5.log)

**Comment by LokeYourLord** [comment]
Yeah same issue, constant crashes on startup with the same issue that @wasabi2016 has. Too sad I cannot use it on my server, practically makes the mod useless.

**Comment by MrJake222** [comment]
Stick to the 1.9.7 for now please
