### ISSUE TITLE
Possible Bug with Dimensions config file when updating to 1.8.9

### ISSUE THREAD

**Issue by ShicKla** [MrJake222/AUNIS#188]
Not sure if intentional or not, but when updating from a prior version to 1.8.9 the `aunis_dimensions.json` file does not get updated with  `"group": "netherOv"` for Nether and Overworld. Is the main config option of `"Does Nether require 8 symbols"` suppose to effect the the group value being inserted in the dimension file? If it does I had mine set to `false`

**Comment by MrJake222** [comment]
I experienced this on my world... This config option got removed, but it still shows up because your config says so. And I cannot update the dimension info because I have no way knowing you're updating or you just removed groups manually.

**Comment by ShicKla** [comment]
Understandable. You may want to let the community know that if they cant dial in or out of the nether with 7 glyphs anymore that they should modify or delete `aunis_dimensions.json`. I am going to go ahead and close this since it is a moot concern.
