### ISSUE TITLE
New event horizon animation is glitchy and looks like the gate

### ISSUE THREAD

**Issue by Luckyradkid1** [MrJake222/AUNIS#189]
please help i really want to have the animation!! what do i do? i have does F3 + T it didnt work.

**Comment by LokeYourLord** [comment]
"pliss halp i rlly wonn haf animaysjun". Dude, first, proper English please, otherwise we can all assume you are 12. Second, you have provided no logs and no screenshots, please provide either and explain what you mean, otherwise you basically just wasted space on the Internet having written this.

**Comment by MrJake222** [comment]
`latest.log` please

**Comment by Luckyradkid1** [comment]
it is english, everything is spelled right gah nvm
