### ISSUE TITLE
Orlin Stargate and the Ancient Analyzer

### ISSUE THREAD

**Issue by oswald2001HD** [MrJake222/AUNIS#190]
As i started a hardcore version with this mod, i found myself with one or rather two problems...

To return to the overworld:

1. Go back to the gate you arrived at
2. Dial Earth

Dial Earth...

WHAT IS THE ADRESSE TO CALL?!?!??!?!?

oh and second i cannot find the analyzer anymore...

is that suppose to happen?

sorry if this looks mean... i am just frustrated, as i do not have any other gate adresses in this world, and i don't wanna cheat to return

**Comment by Luckyradkid1** [comment]
ok, look up earths adress and dial that, seond, the analyzer has been removed, everything the analyzer was used for can now be done without it. also im pretty sure the point of origin for the nether is now serpens caput

**Comment by ShicKla** [comment]
If you traveled to the Nether using an Orlin gate you can use the TV show's address for Earth to get back.
![SGC](https://ih1.redbubble.net/image.154215509.0710/flat,800x800,075,t.u2.jpg)
Also the analyzer was removed a couple versions back.

**Comment by oswald2001HD** [comment]
> If you traveled to the Nether using an Orlin gate you can use the TV show's address for Earth to get back.
> ![SGC](https://camo.githubusercontent.com/8158eda6c1577afdbd3afeee0a2e2e7441393f84/68747470733a2f2f6968312e726564627562626c652e6e65742f696d6167652e3135343231353530392e303731302f666c61742c383030783830302c3037352c742e75322e6a7067)
> Also the analyzer was removed a couple versions back.

**Comment by oswald2001HD** [comment]
> If you traveled to the Nether using an Orlin gate you can use the TV show's address for Earth to get back.
> ![SGC](https://camo.githubusercontent.com/8158eda6c1577afdbd3afeee0a2e2e7441393f84/68747470733a2f2f6968312e726564627562626c652e6e65742f696d6167652e3135343231353530392e303731302f666c61742c383030783830302c3037352c742e75322e6a7067)
> Also the analyzer was removed a couple versions back.

the adress doesn't let me, and i don't know how to find the last symbol...

**Comment by MrJake222** [comment]
If you've recently updated to 1.9.8 you need to delete the `.minecraft/config/aunis_dimensions.json` file or manually add groups to the Nether and Overworld. I'd suggest the former. Because without it the Nether requires 8 symbols(The 6 from the Earth address + Serpens Caput(the arrow thing at the top of the DHD) + Point of Origin (the pyramid thing on the left side of the DHD), both on the outer ring)
