### ISSUE TITLE
Duplicating bug with beamer

### ISSUE THREAD

**Issue by TheRedCreations** [MrJake222/AUNIS#196]
https://discordapp.com/channels/595152041962373120/597869928263057431/712397882308952090
If you put one item in the beamer, on the other end are 4 items.
Version used 1.9.9

**Comment by KamaroTheN7** [comment]
Yep, I have that same.

**Comment by MrJake222** [comment]
The fuck... I can replicate this issue running in normal environment, BUT In dev env running exact same code I'm not... I hate it :/
