### ISSUE TITLE
certain symbol combos don't work with DHD (haven't tried opencomputers yet)

### ISSUE THREAD

**Issue by Hyper-Tex** [MrJake222/AUNIS#197]
Likely won't ever be an issue, but I had an odd bug happen. When I was trying an old address from a gate I broke a while back, it wouldn't let me press the 7th symbol or let me press the big red button to clear it the symbols. Haven't done full testing yet, like breaking the dhd and moving it, but I figured you'd wanna know. Also, I took a screenshot of the symbol combo as I lost the old note page for it
![Screenshot (57)](https://user-images.githubusercontent.com/17879365/82430451-f19fd100-9a52-11ea-9811-bddada44da8b.png)

**Comment by Hyper-Tex** [comment]
the combo on the note page in my hand does work btw

**Comment by MrJake222** [comment]
The Gate at given coordinates does not exist anymore? Also, `latest.log` would be helpful.

**Comment by Hyper-Tex** [comment]
No, but I had the symbol combo page from when I was testing. Weirdly enough, when I do the same with other gate I brake, it lets me press it, and it fails to dial. And it doesn't cause a crash or even errors, it just doesn't let me press the PoO or big red button. 
Also, I just tried to force the gate to accept the address via open computers dialing, that DOES cause a crash, but again, only with that particular combo, in the original intended order. Doing that combo any other way, makes it do a regular dial failure. I'll get the logs to you in a bit. I gotta recreate the crash

**Comment by MrJake222** [comment]
Or just the log on the DHD press failure. It can say a lot (or nothing xD). You can access all your crashes somewhere (.minecraft/crash-logs i think), no need to recreate them

**Comment by Hyper-Tex** [comment]
Okay, I see what the issue was, I'm gonna close this thread. It turned out to be an issue with my single player world. the address was for a broken gate from the 1.9.5 version of the mod. (it was a test world, so i don't worry about it becoming corrupted or anything) Sorry for bothering ^_^
