### ISSUE TITLE
[Suggestion] Subtitle for AUNIS

### ISSUE THREAD

**Issue by weberlepecheur** [MrJake222/AUNIS#199]
Hi,

I suggest you put some subtitle for your mod.
At this hour, when I activate subtitle it show of this :
![image](https://user-images.githubusercontent.com/18701493/82676087-1a3bec80-9c46-11ea-8a78-36b58858750f.png)

**Comment by slava110** [comment]
@MrJake222, shouldn't it be closed?

**Comment by MrJake222** [comment]
I've closed the pull request (rejected it, for other reasons) but i guess we can borrow the captions. That's why separate pull requests is a better approach.
