### ISSUE TITLE
Gliphs stay lit

### ISSUE THREAD

**Issue by lieven121** [MrJake222/AUNIS#2]
Sometimes when failing to dial the glyphs stay lit and from that point on they won't deactivate. Resulting in the ability to turn all of them on (see image).
![image](https://user-images.githubusercontent.com/7773244/60204604-7be5b200-984f-11e9-9d44-79739034dec9.png)

Currently, I have not yet found the excact cause. 
Hard to reproduce

**Comment by PoltixeTheDerg** [comment]
I have encountered this problem before, it always seemed to occur after failed dial attempts multiple times in a row.

**Comment by MrJake222** [comment]
Hope it's fixed. If you reproduce it, feel free to reopen.
