### ISSUE TITLE
Unable to use mysterious pages

### ISSUE THREAD

**Issue by PoltixeTheDerg** [MrJake222/AUNIS#20]
Right clicking with mysterious pages does not seem to do anything.

**Comment by MrJake222** [comment]
Are you in the Overworld?

**Comment by PoltixeTheDerg** [comment]
Yes

**Comment by MrJake222** [comment]
Any output in the console?

**Comment by MrJake222** [comment]
Just tested, I'm experiencing this issue too :/

**Comment by MrJake222** [comment]
However, I'm in the middle of the rewrite, can you please provide the console output to verify the issue?

**Comment by PoltixeTheDerg** [comment]
https://pastebin.com/Sz5UjVBa

this is the console output

**Comment by MrJake222** [comment]
My console output was a little bit diffrent, but probably based on the same thing. Hope it fixed it. I'll release a hotfix on Curse soon.

**Comment by MrJake222** [comment]
https://www.curseforge.com/minecraft/mc-mods/aunis/files/2747609
