### ISSUE TITLE
[Suggestion] Config Transport Rings for Universe Dialer

### ISSUE THREAD

**Issue by weberlepecheur** [MrJake222/AUNIS#200]
Hi,

It seems the universe dialer doesn't refresh the list when you use transport rings with it.

How to reproduce :

I put myself on the bottom layer then use the rings to go middle layer. Then again use the rings to go upper layer but the rings dont move me but instead do that :
![2020-05-22_16 25 02](https://user-images.githubusercontent.com/18701493/82677790-e0201a00-9c48-11ea-8336-2984669b1326.png)

And because of it I can use the rings anymore unless I go out of the range of the universe dialer.

_By the way, why in the config aunis.cfg It said the max radius is 64 but the config default is put at 1024 ?_

**Comment by MrJake222** [comment]
It probably still is connected to the bottom platform. It won't perform a rescan when it's connected. If you need so tight setup of rings, you can lower the radius of the scan. I can technically change it to perform a rescan every second for example but I don't want to put extra load on the server.

I think you're mistaking the Universe Dialer radius(the distance it can detect rings/Stargates) for the `Nearby` mode radius(the distance it can detect other Stargates)

**Comment by weberlepecheur** [comment]
I made the layer in order to put a gate in it, 9 blocks per layer (verticaly). And I fixed this problem by putting 15 blocks per layer. It's pretty huge when making an underground base like SGC.

Can you add a config line in order to reduce the radius scan for rings ?

**Comment by MrJake222** [comment]
It is a config option already. It's called Reach Radius

**Comment by weberlepecheur** [comment]
It is buggy then.

![image](https://user-images.githubusercontent.com/18701493/82707248-feebd400-9c7b-11ea-9a70-201e7f8ff567.png)

From the lower layer i can go to the upper layer and middle layer.
From the middle layer i can only go to the upper layer.
From the upper layer i can only go to the middle layer.

**Comment by weberlepecheur** [comment]
Alright, difficult to handle but i succeed to put a good config ^^
I close the issue
