### ISSUE TITLE
Universe Stargate They are active and facing in and 3 height difference and 3 blocks away cause crash if enter active stargate or grab universe dialer near universe stargate

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [MrJake222/AUNIS#201]
Crash Log: [crash-2020-06-03_16.55.25-server.txt](https://github.com/MrJake222/AUNIS/files/4721769/crash-2020-06-03_16.55.25-server.txt)

Modpack (map included): https://drive.google.com/file/d/1umPMaitueC5iL7JrSoBFml27H9x9MbJL/view?usp=sharing

enter the world "fsifysodifuyaio" and go to Universe Stargate to reproduce

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
ok, this is permanent

**Comment by weberlepecheur** [comment]
A permission is needed to access to your file.

**Comment by weberlepecheur** [comment]
I tried to replicate your issue, but didnt. Instead I got a gate who is stays open, can't dial with it anymore.

![2020-06-05_17 34 02](https://user-images.githubusercontent.com/18701493/83895427-f81c9100-a752-11ea-9087-0739381cf5b4.jpg)

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
yeah, that's talking about edit 1

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
maybe stargates explode when stargate component is broken while open

**Comment by weberlepecheur** [comment]
There no explosion, I was able to re-enter my world using only a nbt editor to delete the dialer from my inventory or else it was the trash can
