### ISSUE TITLE
Dial error from computer

### ISSUE THREAD

**Issue by RedstoneSucht** [MrJake222/AUNIS#21]
I found a error. When I dial from a Computer from a Gate to an other. 
(Dialing 7 Cevrons)The other Gate shows: Chevron 8(bottom right)(https://imgur.com/a/03XzjUM) locked. After shutdown of the Gate is the Chevron is glowing. On the Origin-Gate after shutdown, Chevron 6(https://imgur.com/a/CJQZacN) will not turn off.

(Dialing 8 Cevrons)The other Gate shows: Chevron 9(bottom left)(https://imgur.com/a/fPeO1Mp) locked. After shutdown of the Gate is the Chevron is glowing. On the Origin-Gate after shutdown, Chevron 8(bottom right)(https://imgur.com/a/D6NGP3J) will not turn off.

When I dial from DHD all activated Cevrons will shut down.

**Comment by MrJake222** [comment]
Wow, finally a properly described and very detailed issue ;)

According to additional chevrons lighting up, probably I don't strip the Point of Origin from the address and hence +1 chevron lights up.

I saw the case with 6th chevron on my test world, but I was unable to trace it down to 100% repeatable case... I'll test your case.

**Comment by RedstoneSucht** [comment]
Thank you.

**Comment by MrJake222** [comment]
As it's not game-breaking I'll publish it with next hotfix with bunch of others issues fixed. Maybe even today. Cheers

**Comment by RedstoneSucht** [comment]
Okay. Thank you for this Mod. It is better than the Mod Stargate Network.

**Comment by MrJake222** [comment]
https://www.curseforge.com/minecraft/mc-mods/aunis/files/2747609

**Comment by RedstoneSucht** [comment]
Nice. This Update works. All Chevrons are off after disconnecting.
