### ISSUE TITLE
Event Horizon texture not loading

### ISSUE THREAD

**Issue by Kevlaris** [MrJake222/AUNIS#210]
(This might not be a bug for everyone, but it is for me, since I don't have a beefy computer)

When starting Minecraft, the forge loader always stops for a minute and often freezes when loading textures/tesr/event_horizon_animated.jpg. I have approx. 1800MB of RAM allocated to Minecraft, and when loading that texture, it goes up almost to maximum. I noticed that this texture is a pretty big file.. should consider using a gif (I don't know if it's possible) or using separate images for every frame, or making it so we can disable the animated texture through config files. When activating the stargate, the event horizon is not loaded properly, and is full white. It pretty much ruins the experience lol
Will provide some footage tomorrow, because I'm not at my pc right now

**Comment by MrJake222** [comment]
What GPU have you got and how much video memory (VRAM) do you have? Splitting the file won't reduce it's size... It'll have more, smaller parts. And there is already an option to disable it.

**Comment by Kevlaris** [comment]
Oh.. Haven't really got digging into the config yet, thank you then..
