### ISSUE TITLE
Cannot Open ORLIN Gate

### ISSUE THREAD

**Issue by VenWhoVian** [MrJake222/AUNIS#211]
I just built my first orlin gate in my survival world and I got some power and fueled it up making sure to right click the base block to see that it was indeed full. I then hooked up a lever and some redstone connecting to the back of the orlin gate, and flipped it only to find out that the gate would not power on I tried everything yet the gate will not turn on. help?

**Comment by MrJake222** [comment]
Log?

**Comment by VenWhoVian** [comment]
Which log? The game doesnt crash it just wont open the gate. What log do you need?

**Comment by MrJake222** [comment]
There is a `log` folder in `.minecraft`. The `latest.log` contains the last one. Please provide the last one when the bug occurred.

**Comment by VenWhoVian** [comment]
[latest.log](https://github.com/MrJake222/AUNIS/files/4853792/latest.log)
Also, I was reading some of the closed issues and found someone with a similar problem I increased the energy capacity for the ORLIN gate to 20 000 000 to see if it worked as it did for them, it didn't work but I did not change the value back.

**Comment by VenWhoVian** [comment]
to save you the trouble I think I isolated the issue

[14:32:27] [Server thread/ERROR] [aunis]: Orlin's gate - wrong dialed address
[14:32:32] [Server thread/ERROR] [aunis]: Orlin's gate - wrong dialed address
[14:32:32] [Server thread/ERROR] [aunis]: Orlin's gate - wrong dialed address
[14:32:33] [Server thread/ERROR] [aunis]: Orlin's gate - wrong dialed address
[14:32:34] [Server thread/ERROR] [aunis]: Orlin's gate - wrong dialed address
[14:32:35] [Server thread/ERROR] [aunis]: Orlin's gate - wrong dialed address

was what came up when I flipped the lever
I also found this 

[14:30:15] [Server thread/INFO] [aunis]: [from=OVERWORLD, to=NETHER, isGroupEqual=false]
[14:30:15] [Server thread/INFO] [aunis]: Orlin's dialed address: [Sculptor, Sculptor, Sculptor, Sculptor, Sculptor, Sculptor, Sculptor, Point of Origin]
[14:30:15] [Server thread/INFO] [aunis]: nether address: [Sculptor, Sculptor, Sculptor, Sculptor, Sculptor, Sculptor, Sculptor, Sculptor]

I think the issue was corruption when I updated from the old version of AUNIS to the new one
as one of my mysterious note pages cape up with the same address as the nether address when I updated
Is there anyway to fix this?

**Comment by MrJake222** [comment]
Replacing, resetting the config doesn't work?

**Comment by VenWhoVian** [comment]
Did that
found a file in the world folder named aunis_StargateNetworkData.dat if I understand this correctly that contains the address for the stargate network? I deleted that and well surprise surprise NONE OF THE GATES WORK NOW!!! lol I replaced the file and I have no clue what to do now.

**Comment by MrJake222** [comment]
I said replacing the gate's base block and trying to remove CONFIG file... The one under config folder

**Comment by VenWhoVian** [comment]
I meant did that as in "I already did that and also I did this" either way it didnt work

**Comment by MrJake222** [comment]
You can use NBTExplorer on the file you mentioned. Just remove the `netherGateAddress` tag and save the file. It should try to regenerate the gate. Hopefully with a proper address...

**Comment by VenWhoVian** [comment]
Lemme try that

**Comment by VenWhoVian** [comment]
Just did that

**Comment by VenWhoVian** [comment]
Now the nether gate doesn't have an address

**Comment by MrJake222** [comment]
You mean the Orlin's gate doesn't have it saved or what?

**Comment by VenWhoVian** [comment]
No it just isnt there

**Comment by VenWhoVian** [comment]
I'm artificially recreating it using another address in the nether

**Comment by VenWhoVian** [comment]
Fingers crossed it works

**Comment by VenWhoVian** [comment]
Nope nothing works

**Comment by VenWhoVian** [comment]
I can try and make a new world

**Comment by VenWhoVian** [comment]
[latest.log](https://github.com/MrJake222/AUNIS/files/4854640/latest.log)
This is my latest log from the world I just made I just cant figure out what the issue is, if there is a way I can configure the ORLIN gate to dial a certain address instead of the defaultly configured one please tell me, cause I dont know what to do from here

**Comment by MrJake222** [comment]
I think it's an issue with Biomes O' Plenty

**Comment by VenWhoVian** [comment]
ooooooo

**Comment by VenWhoVian** [comment]
lemme try that

**Comment by VenWhoVian** [comment]
Yep its Biomes
