### ISSUE TITLE
Missing Seventh Glyph

### ISSUE THREAD

**Issue by Froot4** [MrJake222/AUNIS#217]
After smashing my head on my table for two hours trying to get out of the Nether, it comes to my attention that I need seven glyphs to travel cross-dimension, and that the SGC wiki only has six listed for Earth. I can't figure out what the seventh is for the life of me, and am now stuck in the Nether. How the heck am I supposed to find the seventh? I just used the Orlin Gate to get here and now can't get back through the portal I came out of.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
easy, point of origin
