### ISSUE TITLE
[suggestion] stop the gate whit a command run in a pc (opencomputer)

### ISSUE THREAD

**Issue by VinczDav** [MrJake222/AUNIS#221]

**Comment by PoltixeTheDerg** [comment]
do you mean close the gate? if so that's already a thing

**Comment by VinczDav** [comment]
How you can close, or shutdown the gate whit a command in an opencomputer pc?

**Comment by PoltixeTheDerg** [comment]
look at the wiki

**Comment by VinczDav** [comment]
This? "disengageGate()"
How can i use this?

**Comment by PoltixeTheDerg** [comment]
you can either use the interpreter or write a program, either way it does not belong here so please close this issue and the previous 2 you made
