### ISSUE TITLE
[Computercraft] Beamer adress disappears after reloading savefile

### ISSUE THREAD

**Issue by Charlesthepenguin** [MrJake222/AUNIS#222]
The component adress for Beamer block is not saving. 

Log: [19:31:03] [Server thread/WARN] [opencomputers]: A component of type 'beamer' disappeared (ea9ef996-9c84-44d3-a6ab-af87b1db778b)! This usually means that it didn't save its node.

Instead its generating a new adress.

This happens for all beamer blocks ingame after reloading savefile.
All other blocks save thier adress, so im figuring it might be something with the code itself with the block. Not opencomputers

**Comment by MrJake222** [comment]
Huh I've fixed this one on the gates. Seems to affect other blocks as well :/
