### ISSUE TITLE
Universe gate placed by loading structure crashing game

### ISSUE THREAD

**Issue by RoboticSith** [MrJake222/AUNIS#223]
I am assembling a modpack with the intent of using the stargates to navigate various dimensions to progress through a quest tree. My plan was to use the Universe style gates and put them in a specific chunk (as part of a structure) when a given dimension is first loaded that way, the address would be constant even though the terrain would be different from game to game.  I can successfully save the entire gate and surrounding blocks to a structure however, when I load that back in, it is maintaining the same address as the 'template' gate used to create the structure (all still in the same dimension for now).  When I then try to break parts of the gate to reset/recalculate the address, it does one of two things...
1) Block breaks (and drops) but model sometimes does not de-render and the block is usually still there but now invisible.  Replacing said block reforms the gate, but the address does not change.  Any subsequent interfacing with the gate causes the game to crash about 80% of the time.
2) Game freezes and crashes right away.  Crash log attached.

Something interesting that I noticed during all of this, if I don't break any blocks and instead open the gate's GUI, I can then insert a crystal or capacitor, close the GUI, fly to the original gate a few chunks away and open it's GUI, and retrieve those same items.

I'm using version 1.12.2-1.9.8-beta since I ran into a number of issues with version 1.12.2-1.9.9-beta on a different modpack project (issue #204)

[crash-2020-07-31_15.12.56-client.txt](https://github.com/MrJake222/AUNIS/files/5008782/crash-2020-07-31_15.12.56-client.txt)

**Comment by MrJake222** [comment]
You can try running `/sgprepare` when looking at the base block before saving it.

**Comment by RoboticSith** [comment]
Thanks, I somehow missed the list of commands on the wiki.  Unfortunately, it did not resolve the core issue.  When I run the command, I get the chat message "preparing StargateUniverseBaseTile" so I'm assuming the command worked (I didn't open the GUI to check since I'm assuming that would reset the gate and undo what the command did).  Whenever I try to save the structure after running the command, it refuses to save (no error messages or feedback), the structure block GUI just closes.  When I look in the log file, it is showing that it couldn't set the structure block because of a NullPointerException for the stargate base tile.  Removing the entire gate and rebuilding it along with quitting and reloading the world also do not help.
[latest.log](https://github.com/MrJake222/AUNIS/files/5011452/latest.log)
