### ISSUE TITLE
DHD Inner symbols fix

### ISSUE THREAD

**Issue by Geocube101** [MrJake222/AUNIS#226]
*Im not entirely sure how to implement this so imma just leave the files*
The inner symbols on the DHD are rotated almost 180 degrees from where they should be
(This is just your original model with the inner symbols rotated to match their actual positions)

The blend, obj, and mtl files
[DHD-fixed](http://www.mediafire.com/file/2kvg1oyjm5xfpoh/DHD-Fixed.zip/file)

**Comment by MrJake222** [comment]
It was discussed on Discord and I won't be fixing that. Too much hassle vs almost 0 profit.

**Comment by Geocube101** [comment]
Ok nice to know
*(i had already fixed the DHD model just didn't know how to implement it for a pull request)*
