### ISSUE TITLE
animated event horizon dosnt work on linux

### ISSUE THREAD

**Issue by Luckyradkid1** [MrJake222/AUNIS#227]
self explanitory, i have linux, and it dosnt work, KamaroTheN7 tested it on widows (the computer has same GPU, but my CPU is stronger), and KamaroTheN7 said it does work on theirs. im not sure if this can be fixed, but who knows... what it shows on my computer is like a white and grey and black and constantly changing in those colors.

**Comment by MrJake222** [comment]
I literally use linux to develop this mod lol. So what GPU do you have? Is it a dedicated one? How much memory does you GPU have (VRAM)?

**Comment by Luckyradkid1** [comment]
oh lmao. intel gpu i think, dedicated, and 1 gb vram. so its teh vram xD. sry for this

**Comment by MrJake222** [comment]
So Intel or dedicated? XD

Hmm 1gb is quite big though...

**Comment by Luckyradkid1** [comment]
oh lmao got that wrong very sorry.
um, its like AMD or radeon? or something like that. dedicated.
if im not helpful (which im not) u can figure it out, i have elitebook 8470p laptop. i cant change the gpu so... ye what google says is what it is

**Comment by MrJake222** [comment]
Can you check your video ram please?
Here is a tutorial https://www.cyberciti.biz/faq/howto-find-linux-vga-video-card-ram/
I think the `sudo lshw -C display` is the simplest command to check it, but you may need to install it by `sudo apt install lshw` (assuming you're using Ubuntu)

**Comment by Luckyradkid1** [comment]
not using ubuntu, im using linux mint. but ok ill try

**Comment by Luckyradkid1** [comment]
1 GB

**Comment by Luckyradkid1** [comment]
Ok I got aunis on a better computer I have, it's also Linux, and it worked. So it's my laptop. Sry lol
