### ISSUE TITLE
File event_horizon_animated crashing my minecraft during stage 5/7 on forge

### ISSUE THREAD

**Issue by captinwill** [MrJake222/AUNIS#230]
When I try to get in to Minecraft, I am unable to go farther than stage 5/7 on forge because file event_horizon_animated is crashing my game.

**Comment by MrJake222** [comment]
Log?

**Comment by captinwill** [comment]
here is the log

[crash-2020-09-15_17.21.45-client.txt](https://github.com/MrJake222/AUNIS/files/5228390/crash-2020-09-15_17.21.45-client.txt)

**Comment by MrJake222** [comment]
Log clearly says you're out of memory. Declare more RAM for your game

**Comment by captinwill** [comment]
ok

**Comment by captinwill** [comment]
Thanks it worked
