### ISSUE TITLE
Biomes O' Plenty Error

### ISSUE THREAD

**Issue by VelociraptorsofSkyrim** [MrJake222/AUNIS#233]
For some bizarre reason, when you have Biomes O' Plenty installed, the Orlin gate seems incapable of accepting a Redstone signal.

**Comment by MrJake222** [comment]
It's not about redstone... Biomes O'Plenty fucks up Nether dimension in a weird way and Orlin's has problem loading it.

**Comment by VelociraptorsofSkyrim** [comment]
Ahhh. My mistake.

**Comment by zendiik** [comment]
On BoP Orlin gate still not working. Energy works, but nether gate not connect.

```
[Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] Energy stored: 17,820,000 RF (Required: 8,604,056 RF, 0.00 s)
[Server thread/ERROR] [aunis]: Tried to perform a group check for a non-existing dimension. This is a bug.
[Server thread/ERROR] [aunis]: Orlin's gate - wrong dialed address
[Server thread/ERROR] [aunis]: Tried to perform a group check for a non-existing dimension. This is a bug.
[Server thread/ERROR] [aunis]: Orlin's gate - wrong dialed address
```

**Comment by MrJake222** [comment]
Are tou sure you're using the latest version?

**Comment by slava110** [comment]
It is not latest version probably. Cause I've added more error information to config

**Comment by MrJake222** [comment]
Yeah...

**Comment by zendiik** [comment]
Is 1.9.11-beta from CurseForge latest?

**Comment by MrJake222** [comment]
Yes

**Comment by zendiik** [comment]
Ok, that bug is from the latest version.

**Comment by MrJake222** [comment]
I literally have no idea how the fix didn't reach Curse... The `1.9.11` on Curse just doesn't have the fix implemented. Hold on, I'll upload correct version in a few minutes. If the bug persists please include new log (It's more verbose).

**Comment by MrJake222** [comment]
Please redownload [this file](https://www.curseforge.com/minecraft/mc-mods/aunis/files/3156118) and let un know!

**Comment by zendiik** [comment]
Now it works, thanks
