### ISSUE TITLE
Universe Dialer - Switch between Address and Name

### ISSUE THREAD

**Issue by TheRedCreations** [MrJake222/AUNIS#234]
If posible add names to the Universe Address

**Comment by MrJake222** [comment]
I don't think there is enough space on the remote for that 🤔

**Comment by Geocube101** [comment]
Could have a key-bind to show additional info for the selected address (like name, position etc...)

**Comment by TheRedCreations** [comment]
Maybe a key-bind to switch from address to name

**Comment by MrJake222** [comment]
That's actually good idea @TheRedCreations

**Comment by TheRedCreations** [comment]
Done in Alpha 2021-02-08
