### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by SinonTechnicolour** [MrJake222/AUNIS#239]
Things like the stargate gui aren't appearing

Also, this mod needs tutorials. I am kinda confused and i have a decent knowledge of the stargate franchise, if there were youtube tutorials i think it would make it a lot easier for people to approach this mod, a suggestion not a complaint.

Also my game always freezes when loading a single texture though i wouldnt be able to tell you which. Just letting you know on this point.

**Comment by MrJake222** [comment]
Have you checked the wiki? https://github.com/MrJake222/AUNIS/wiki/Stargate-(General) - This page has some pretty extensive info on Stargate operations. Also the Getting started page is available.

You're clicking the gate and nothing happens? Any log info?

**Comment by SinonTechnicolour** [comment]
Thanks for the quick reply! I will get it now, though the problem (and this may just be my lack of know how) but basically the notebook pages won't link and the stargate universe dialer i can't controll (what are the normal controlls to use it as it may just be me being wrong) 


Thanks for the link i will check it out.

**Comment by SinonTechnicolour** [comment]
sorry knew to github not sure how the to add a file. (lol sorry)

**Comment by PoltixeTheDerg** [comment]
> Thanks for the quick reply! I will get it now, though the problem (and this may just be my lack of know how) but basically the notebook pages won't link and the stargate universe dialer i can't controll (what are the normal controlls to use it as it may just be me being wrong) 
> 
> 
> Thanks for the link i will check it out.

The keyboard controlls are in options

**Comment by SinonTechnicolour** [comment]
how do I link gates then? 

Also still have the issue with the right clicking with notebook page not working.

**Comment by SinonTechnicolour** [comment]
I was being stupid! Just read the wiki link provided by Jake222! Cheers guys really nice to have a community happy to answer questions from noobs like me! 

Also Jake222 nice job with the mod! Loving it so far!
