### ISSUE TITLE
Little Problem with Sound and Visual

### ISSUE THREAD

**Issue by RedstoneSucht** [MrJake222/AUNIS#24]
I will send you a videolink about our problem.

**Comment by RedstoneSucht** [comment]
https://youtu.be/G9oY__CivOk

**Comment by MrJake222** [comment]
Can I get the source code of the Lua program used? You sure you're not performing multiple engageSymbol calls?

**Comment by RedstoneSucht** [comment]
the Luaprogram ist that, you gave on github. even without the computer its doing the same

**Comment by MrJake222** [comment]
Try restarting the computer XD

When you interrupt the program in the middle it doesn't clear it's events and thus calling engageSymbol multiple times...

You don't have multiple computers running the same program in your network, do you?

**Comment by RedstoneSucht** [comment]
It's not a problem with the computer. We hear at locking a chevron no sound. The same with the ringtransporter. In the video you can see locking chevrons without sounds. And the chevron on the top is lagging. We use this mod on a little Multiplayer Server. In Singleplayer are no problems.

**Comment by RedstoneSucht** [comment]
I try to explain. I play with 2 other Users on a Multiplayer Server. On this server we use your mod. When we use the Stargate, we hear only: Ringrotation, Eventhorizont, deactivating Stargate and the errorsound on the dhd. On the Visual side, at dialing the Chevron on the top is lagging(shown in Video).
