### ISSUE TITLE
Notebook Page doesn't display in full on a 4:3 display

### ISSUE THREAD

**Issue by Hawkfang42** [MrJake222/AUNIS#246]
yeah, my computer monitor is 4:3, that's how I know, part of the page is too far to the side, making it so I have to flip between main hand and offhand, or I can't see the column furthest to the side

**Comment by MrJake222** [comment]
When I release 1.9.12 go to <ESC> -> Mod Options -> AUNIS -> Config -> Audio/Video -> Notebook Page offset and enter 0.2 or greater value (test what works best).
