### ISSUE TITLE
Universe dialer looks weird with item frame

### ISSUE THREAD

**Issue by slava110** [MrJake222/AUNIS#251]
![dialerglitch](https://user-images.githubusercontent.com/26705162/103306247-2aa71780-4a1e-11eb-8e75-8e47eac27518.png)
Should be possible to fix by `stack.isOnItemFrame()` check here
https://github.com/MrJake222/AUNIS/blob/master/src/main/java/mrjake/aunis/item/dialer/UniverseDialerTEISR.java

**Comment by MrJake222** [comment]
Notebook page had similar issue. See `TransformType` somewhere in baked models.
