### ISSUE TITLE
Disable snow forming on stargate

### ISSUE THREAD

**Issue by slava110** [MrJake222/AUNIS#255]
![unknown-4](https://user-images.githubusercontent.com/26705162/103419037-4dfacf80-4ba2-11eb-935b-cca2cad8c797.png)

**Comment by MrJake222** [comment]
I've seen someone fixing this by making the bounding boxes 1.001 high or so

**Comment by slava110** [comment]
I've seen something like overriding single method in Fureniku's roads

**Comment by TheRedCreations** [comment]
maybe that should be fixed at the dhd too

**Comment by slava110** [comment]
Same stuff with DhD? Okay. I'll check it out when I'll be home. Or Mr. Jake will fix it :shrug:
