### ISSUE TITLE
Blinking Eventhorizon

### ISSUE THREAD

**Issue by ZeroPointTwitter** [MrJake222/AUNIS#261]
hey, i have a bug, i have my ram for mc at 7GB but if a have Animated eventhorizon on, the event horizon is starting to blink fast grey and white wehn i open the stargate

https://youtu.be/4QalREz45e4

 here the vid, and if its not working, look atb the YT Channel (Zero Point Twitter) i made mc vids, the newest one

**Comment by MrJake222** [comment]
But what's your video ram?

**Comment by ZeroPointTwitter** [comment]
Video ram? Where can u check this

**Comment by ZeroPointTwitter** [comment]
> But what's your video ram?

128 mb

**Comment by MrJake222** [comment]
At least 10 times too small
