### ISSUE TITLE
Not able to dial a 9 chevron address with Milkyway DHD

### ISSUE THREAD

**Issue by Warp8** [MrJake222/AUNIS#266]
I believe the issue is specifically that I can't put more than one DHD crystal in the DHD. I am using version 1.9.12 Alpha 21-01-14.

https://user-images.githubusercontent.com/22381811/105100715-b50df480-5a7b-11eb-8aa4-64ffc8036200.mp4

**Comment by MrJake222** [comment]
I'm pretty sure you never could insert 2 upgrades, but hey, I don't remember everything.... I'll look into it ;)

**Comment by MR-Spagetty** [comment]
in previous versions you needed 1 upgrade for 8 chevron dialing and another for 9 chevron dialing

**Comment by MrJake222** [comment]
Oh god even the wiki has a screenshot of 2 upgrades.... https://github.com/MrJake222/AUNIS/wiki/Dial-Home-Device-(DHD)#control-crystal

**Comment by MR-Spagetty** [comment]
nice

**Comment by slava110** [comment]
Oh... Didn't know about that, sorry :x

**Comment by MrJake222** [comment]
@slava110 If you plan on fixing that, you can make one upgrade sufficient for 9 symbols.

**Comment by slava110** [comment]
> If you plan on fixing that, you can make one upgrade sufficient for 9 symbols.
@MrJake222 you mean additional upgrade or make existing able to dial 9 symbols?

**Comment by MrJake222** [comment]
Existing able to dial 9. It's dumb to have 2 pieces of the same upgrade do a different thing than one. Maybe I'll adjust the craftings :p

**Comment by Manglefan** [comment]
in the wiki it explains how to dial cross dimensions you put the first 6 the any one of the dimensional symbols then the earth symbol

**Comment by MrJake222** [comment]
What?
