### ISSUE TITLE
Crash when aborting dial using Universe Dialer

### ISSUE THREAD

**Issue by Dragobot519** [MrJake222/AUNIS#269]
Ran into a bug with all current versions of the alpha branch, if you begin to dial using the Universe Dialer and then abort at any stage of the dial, the world will crash and will crash with every attempt to reload. This was a singleplayer test world with only aunis installed:
[crash-2021-01-25_22.37.59-server.txt](https://github.com/MrJake222/AUNIS/files/5870147/crash-2021-01-25_22.37.59-server.txt)

**Comment by MrJake222** [comment]
Can you upload the crashing world here?

**Comment by Dragobot519** [comment]
I don't have the exact world that log was pulled from as I  deleted and remade the worlds several times to test but the bug is easily reproducible.
[New World.zip](https://github.com/MrJake222/AUNIS/files/5872263/New.World.zip)

**Comment by MrJake222** [comment]
https://github.com/MrJake222/AUNIS/blame/master/src/main/java/mrjake/aunis/tileentity/stargate/StargateAbstractBaseTile.java#L555-L557
@slava110?

**Comment by slava110** [comment]
> The gate fails to dial and you add a task on the (even possibly non-exisisting) gate?

IIRC I've added it because gate chevrons on second gate remain turned on after dialing failed. But forgot to add checking for address

**Comment by MrJake222** [comment]
@slava110 have a look at the commit above. The thing is the `incomingWormhole` should never reach the target gate (when the dialing is destined to fail, for ex. not enough power). Find me a testing case when I can develop a nice system for this corner-case.
