### ISSUE TITLE
Activation code doesn't work through opencomputers

### ISSUE THREAD

**Issue by TheoChronologic** [MrJake222/AUNIS#27]
When using the app displays an error and I do not know how to solve it, the application worked 2 days ago without problems, and what with it now I do not understand
![IMG_20190728_021828](https://user-images.githubusercontent.com/46673958/62000370-05ea9a00-b0de-11e9-98cf-84e9d70b64ae.jpg)
![IMG_20190728_021824](https://user-images.githubusercontent.com/46673958/62000371-05ea9a00-b0de-11e9-9d8a-5a94b14a719a.jpg)

**Comment by PoltixeTheDerg** [comment]
This looks like the stargate isn't connected or at least isn't being detected by the computer
