### ISSUE TITLE
Error while placing ring blocks next to gate base

### ISSUE THREAD

**Issue by TheGNinja** [MrJake222/AUNIS#272]
Not sure how to explain it but there was an error while placing ring blocks next to gate base while I was trying to build a stargate

Edit:
I got the error here now, It is right when you place the ring block next to base block
`The game crashed whilst tesselating block model
Error: java.lang.ClassCastException: mrjake.aunis.tileentity.StargateBaseTile cannot be cast to mrjake.aunis.tileentity.StargateMemberTile
Exit Code: -1`

**Comment by MrJake222** [comment]
Can you provide a full crash log?

**Comment by TheGNinja** [comment]
Kinda new to crash reporting where would I find the files?

**Comment by TheGNinja** [comment]
[crash-2021-01-30_23.02.30-client.txt](https://github.com/MrJake222/AUNIS/files/5898893/crash-2021-01-30_23.02.30-client.txt)
nvm found it

**Comment by TheGNinja** [comment]
Forgot to add that it seems to be with the Chevron blocks aswell as ring blocks

**Comment by MrJake222** [comment]
Wtf why are you using so ancient version of aunis.... 1.3 beta? Please update.

**Comment by TheGNinja** [comment]
I've updated and now is crashing differently on loading...

**Comment by MrJake222** [comment]
Please try updating java and forge
