### ISSUE TITLE
Beamers revamp

### ISSUE THREAD

**Issue by MrJake222** [MrJake222/AUNIS#273]
### Next version

- [x] Add signals (in modifiable intervals) about power/fluid/item transferred
- [x] Add configurable gate-to-beamer distance
- [x] Make beam color responsive to fluid color
- [x] **Nerf the recipe**

### Maybe another time
* ~~Make items transport occuring once in 10 ticks for ex.~~
* ~~Render items inside the item beam~~
* ~~Damage dealt by beams~~

**Comment by TheRedCreations** [comment]
A question, what do you mean with that?
![grafik](https://user-images.githubusercontent.com/35812887/106516045-cffa5300-64d6-11eb-9677-e243857d38b2.png)

**Comment by MrJake222** [comment]
Gate beamer distance

**Comment by TheRedCreations** [comment]
Ah. ty

**Comment by Geocube101** [comment]
_Currently making a beamer program_
Could you add a method to get the beamer's redstone control state?
