### ISSUE TITLE
Bug with the notebook

### ISSUE THREAD

**Issue by HDL34** [MrJake222/AUNIS#277]
Minecraft crashes when I take the notebook.
https://github.com/MrJake222/AUNIS-pages/files/5938556/crash-2021-02-05_17.57.30-client.txt
See attached video:
https://user-images.githubusercontent.com/61374058/107141685-d0f21100-692a-11eb-861f-d424a7a9005d.mp4

**Comment by Cronosus** [comment]
i think i can easily anfer that myself
do not give yoursel notebook from nei/creative
this item is crafter by combining notes. if you give yoursel empty one, it has "null" data, and that why it crashes

**Comment by MrJake222** [comment]
Bit it shouldn't crash lol
