### ISSUE TITLE
Beamer crash - latest alpha

### ISSUE THREAD

**Issue by TheRedCreations** [MrJake222/AUNIS#285]
The Beamer was on one side 12 blocks away from the Eventhorizont. On the other side it was below 10 blocks
[crash-2021-02-11_19.01.07-server.txt](https://github.com/MrJake222/AUNIS/files/5967501/crash-2021-02-11_19.01.07-server.txt)

**Comment by MrJake222** [comment]
It crashed out of itself or you did something specific?

**Comment by TheRedCreations** [comment]
It crashed itself after open the gate

**Comment by MrJake222** [comment]
You turned the beamer around or sideways, didn't you?

**Comment by TheRedCreations** [comment]
The beamers are facing the gate on both sides

**Comment by MrJake222** [comment]
Hmm, I was able to replicate the issue with beamers facing random ways (exact same crash stack trace). I'll fix it and you can test it in your setup.

**Comment by MrJake222** [comment]
I've also changed up linking code a little bit. Beamers will not connect to beamers found in the line of scanning but connected to another gates. Like this:
![beamers](https://user-images.githubusercontent.com/7581790/107761571-ddf87100-6d2b-11eb-9fcb-a8acd2a2da50.jpg)

**Comment by TheRedCreations** [comment]
Beamers work now fine
