### ISSUE TITLE
Return event for Stargate failure while open

### ISSUE THREAD

**Issue by Geocube101** [MrJake222/AUNIS#29]
Addition of an event for when the stargate unexpectedly closes after successful dial
(Power requirements to sustain wormhole no longer met)

**Comment by MrJake222** [comment]
The gate emits "stargate_closed" in my testing envionment. You want a variable to differentiate the power case from normal close?

**Comment by Geocube101** [comment]
Yeah sure, it would allow some diversity in lua computer scripting on why the gate closed.
Maybe a "stargate_failed_no_power" or something.
_Also, this is optional as I probably won't use it, but a message to indicate if the receiving gate (the gate you dialed to) mysteriously disappears; like a "starget_failed_connection_lost", as there are some times where the other gate is destroyed so the connection closes_
