### ISSUE TITLE
[ENH/BUG] Gate dialing

### ISSUE THREAD

**Issue by JustWolfii** [MrJake222/AUNIS#292]
As seen in Stargate SG-1, when a gate was dialed, it was lightning up the chevrons one by one as they were locked on the dialing gate (on incoming wormhole). Currently it just lights up all chevrons at once when dialing is finished.

**Comment by MrJake222** [comment]
No time for that. User can press BRB faster than the gate lights up.

**Comment by JustWolfii** [comment]
I think that it would be possible to make it somehow, but for now, I'll close this issue and reopen it once I get any idea and maybe I'll test it by myself first. Anyway, thanks for making (I believe I can say) the best Stargate mod!
