### ISSUE TITLE
Capacitor draining instantly

### ISSUE THREAD

**Issue by ConnorVex** [MrJake222/AUNIS#293]
I am on a multiplayer server using ANUIS. Whenever I use a capacitor, or pull a full one out of my inventory, it goes instantly down to 0. I have a clip to show what I mean.

https://medal.tv/clips/44924936/d13379hlJxXO

I have no clue if this was reported before.

**Comment by slava110** [comment]
Mod version?

**Comment by ConnorVex** [comment]
> Mod version?

1.9.11-beta

**Comment by slava110** [comment]
Fixed in alpha versions already
