### ISSUE TITLE
Can't start it up

### ISSUE THREAD

**Issue by kungstoffe08** [MrJake222/AUNIS#294]
Can you please fix my problem? im only trying to play it in my minecraft launcher on forge but aunis is the only problem. if i want to play it, i must use modpack created by someone another. Please, help me:
 [crash-2021-02-26_12.11.14-client.txt](https://github.com/MrJake222/AUNIS/files/6049259/crash-2021-02-26_12.11.14-client.txt)

**Comment by MrJake222** [comment]
Try allocating more RAM to your Minecraft installation. If that's not an option try manually disabling the animated event horizon texture in `.minecraft/config/aunis.cfg`.

**Comment by MrJake222** [comment]
Change
`B:"Disable animated Event Horizon"=false`
to
`B:"Disable animated Event Horizon"=true`

**Comment by kungstoffe08** [comment]
It didn't helped. The only version i can open is 1.8.3. Sending crash report:
[crash-2021-02-26_12.11.14-client.txt](https://github.com/MrJake222/AUNIS/files/6055587/crash-2021-02-26_12.11.14-client.txt)

**Comment by MrJake222** [comment]
You clearly need more RAM

**Comment by kungstoffe08** [comment]
Problem solved, i didn't knew how to set RAM, so i googled and added 2 more GB (now it's 3GB RAM) and its working, so now i just need to transfer saves to make sure everything is where it's supposed to be. Thanks a lot man, aaaand will u do something with that orlins gate? and will you add pegasus gates?? (milky way to overworld, universe for nether and pegasus for the end, aaand will you wake gates generate even in the nether and end dimensions???)

**Comment by MrJake222** [comment]
What about orlin gate?
Pegasus? Someday yes
Generation? We'll see...

**Comment by kungstoffe08** [comment]
Alright, and (maybe) last few things: i setted that 
`B:"Disable animated Event Horizon"=true`
 back to 
`B:"Disable animated Event Horizon"=false`
 and its working,
and how can i change the name of notebook page??
Oh, and last thing i'd like to say now is that this 
(for now) is my only way to contact you, so yes, that it. Thanks for every thing and i will hold this open (if you won't colse it) so i can concact you. Thanks for everything.

**Comment by kungstoffe08** [comment]
Oh, just discoverd that you can't dial uneverse gate from milky way gate. Can u tell me fow to fix it or do something with it, please?

**Comment by MrJake222** [comment]
Use discord. What do you mean you can't dial. What happens?
Also read the wiki here on GitHub.
https://github.com/MrJake222/AUNIS/wiki/Notebook-Page

**Comment by kungstoffe08** [comment]
i made video but its too big (163 MB) and discord can send max 8 MB videos and this can send only 10 MB so how can i send it to you??

**Comment by MrJake222** [comment]
Mega, Mediafire?

**Comment by MrJake222** [comment]
Google drive?

**Comment by kungstoffe08** [comment]
I totally forgot about the google drive so i upload it there and here goes url:
https://drive.google.com/file/d/1IqwtoQpvn-vSyCwy1t0m-M7MZDSMSHZ-/view?usp=sharing
try to do something with it please or, is it a bug??

**Comment by kungstoffe08** [comment]
oh, and can u create command to find gates?? i mean closest gate and list of gates??

**Comment by MrJake222** [comment]
Sent permission request for the Google drive file.

`/sgquery`

**Comment by MrJake222** [comment]
https://github.com/MrJake222/AUNIS/wiki/Dial-Home-Device-(DHD)#dhd-glyph-upgrade

**Comment by slava110** [comment]
@kungstoffe08, problem solved?
