### ISSUE TITLE
Can't create new world

### ISSUE THREAD

**Issue by kungstoffe08** [MrJake222/AUNIS#297]
I can't create new world in AUNIS_1.9.11_beta, crash report included 
[crash-2021-03-21_20.51.39-server.txt](https://github.com/MrJake222/AUNIS/files/6178224/crash-2021-03-21_20.51.39-server.txt)

**Comment by MrJake222** [comment]
Crash report doesn't have anything to do with Aunis :thinking: 
Does it work without Aunis?

**Comment by kungstoffe08** [comment]
sorry for being inactive for so long but i tryed without aunis and then with aunis and now i can create new for like nothing happened. thanks for helping and contact me at discord server with this: @[ლ(ಠ益ಠ)ლ]
