### ISSUE TITLE
bug capacitor wit universe gate in the last alpha mod

### ISSUE THREAD

**Issue by HDL34** [MrJake222/AUNIS#298]
Only on the universe gate, there is no way to insert capacitors.
See the attached video. There are already 2 but they are the 2 added on the previous alpha.
https://user-images.githubusercontent.com/61374058/112011209-52db7980-8b28-11eb-8244-49d6a11f77fa.mp4

**Comment by MrJake222** [comment]
It's intended. Universe gate was nerfed. It's configurable though.

**Comment by HDL34** [comment]
Yes, I checked and indeed, I could change the default value (0) by the value (3).

**Comment by slava110** [comment]
@MrJake222, but capacitor slot should be hidden probably, right? _And what to so with old capacitors, placed before alpha like in this case_?

**Comment by MrJake222** [comment]
They should be crossed out. And you can pull out the old ones i think.
