### ISSUE TITLE
List all stargates in world?

### ISSUE THREAD

**Issue by VoxelTek** [MrJake222/AUNIS#301]
Hi there,
I'm sorry to be posting another issue so soon, however, an issue (not a bug) has arisen. I teleported to a random location, and created a stargate there, however, I accidentally used it to get to another stargate of mine. I forgot to grab the address before I left, so I was wondering, is there any way I can look at the stargates that exist in a world, and grab their addresses? Otherwise, this stargate will be lost forever to me.
Thanks,
VoxelTek

**Comment by MrJake222** [comment]
`/sgquery`
https://github.com/MrJake222/AUNIS/wiki/Console-commands#console-commands

**Comment by VoxelTek** [comment]
> `/sgquery`
> https://github.com/MrJake222/AUNIS/wiki/Console-commands#console-commands

ah, sorry. i missed that. Thank you!
