### ISSUE TITLE
Having beamer connect thru gate instantly crashes

### ISSUE THREAD

**Issue by captinwill** [MrJake222/AUNIS#306]
[crash-2021-04-24_09.07.17-server.txt](https://github.com/MrJake222/AUNIS/files/6369645/crash-2021-04-24_09.07.17-server.txt)
Aunis
Security craft
Actually Additions
Advanced Rocketry
Aether II
The Aether
Ambient Sounds
Antique Atlas
Armor Under
AutoReglib
Baubles
BetterFPSMod
Botania
BrandonsCore
Carrotslib
Carryon
Mo'Chickens
CodeChickenlib
CoFH Core
CoFH World
conarm
controllable
coroutil
CreativeCore
Cucumber
DavincisVessles
drawbridges
Dupechest
EnderCore
EnderIO
Euhdawsons Gravestone mod
ExnihilioCreatio
Extra Planets
ExtraUtilities2
Extreme Reactors
Forgelin
Galacticraft Core
Galacticraft Planets
Hachery
Hwyla
iChunutil
Immersive Engineering
Immersive Inteligence
JEI
Lib Vulpes
library
lost aether content
malasis core
malasis doors
Mantle
MicDoodle core
MJRLegendsLib
Moving World
Mowzies Mobs
Mystical Agriculture
Open Computers
Ore Excavation
p455w0rdslib
Portalgun
Project Lambda
Psi
Radekt TF2 Weapons
RikMuldsCore
SCP lockdown
Serene Seasons
SGCraft
Simple Generators
Spartan Shields
Spartan Weaponry
Tinkers Construct
Thermal Expansion
Thermal Foundation
Tinker Tool leveling
Tough as Nails
Tough Expansion
Tree Growing Simulator
Valkarie lib
vanilla fix
Waystones
Wearable backpacks
Weather2
Xaeros Minimap
Xaeros World map
Zero core
here is my mod list

**Comment by MrJake222** [comment]
Please use latest alpha from GitHub releases. The beamer got some work there. The alpha is pretty much done except I don't have time to fix some minor bugs and push the beta.

**Comment by captinwill** [comment]
well how do i install the files
