### ISSUE TITLE
Suggestion: some way to customize the Stargate's address

### ISSUE THREAD

**Issue by JamesTheMaker** [MrJake222/AUNIS#308]
It would be awesome if you could add some way to customize the address of a Stargate. Could be an admin tool, could be a craftable item, idc. I just would really appreciate the ability to set my own addresses.

**Comment by MrJake222** [comment]
Read the wiki, please.... There is a command that just does that.

**Comment by JamesTheMaker** [comment]
oh, I'm sorry. I didn't notice that before. Thank you!
