### ISSUE TITLE
Ring Transporter Diameter Larger then Canon

### ISSUE THREAD

**Issue by ShicKla** [MrJake222/AUNIS#31]
Not sure how close this mod is trying to be accurate to the shows canon, but I did notice the mod's ring transporters are on the large size. According to canon the outer diameter of the rings are about 3.6 m. Now if you did the rings strictly to that size it would make the teleport area in Minecraft only 1 square block. Even I recognize that is too small of an area, so I suggest do a diameter of 5 m. At that diameter you can have the teleportation area be 3x3 m.

Of course this is nothing but a suggest, and as far as I know you already took the diameters in to account and made a choice to just have the transporters that large. In which case, just keep doing your thing making this mod awesome, because as a SG fan I love it.

**Comment by craft90** [comment]
I imagine the size is the way it is to account for a correct number of chevrons. Unlike the original Greg's SGcraft that lacked two (cos he didn't notice them when making the model)

**Comment by MrJake222** [comment]
Wow, I just cut the scale down a half and now I see the big ones as they were planned for elephants or something...
