### ISSUE TITLE
Asigning blocks as Camo Can cause server crash.

### ISSUE THREAD

**Issue by CalcipherD** [MrJake222/AUNIS#32]
Assigning some blocks from other mods as Camo causes the game to crash.
Opening the game again causes it to crash immediately upon loading that block.

Does not occur with all blocks, but once a problem block is found, it is easy to replicate.

So far, I have found issues with blocks from Immersive Engineering, Quark, and Better With Mods.

Here is an example Crashlog for one item tested.
https://paste.dimdev.org/dojaxuqopi.mccrash

**Comment by ShicKla** [comment]
@MrJake222
As a possible stop gap, until you can figure out a solution to make the modded blocks work, would be a Try/Catch when the method gets the blocks properties. On failure you just have it spit the block back out, as if you are removing the camo with the right-click.

**Comment by MrJake222** [comment]
Right now I've blocked the crash. Normal block model is shown where the not supported block would show. If you really need one of those, please create separate issues.
