### ISSUE TITLE
ENH: Propagate OC Wireless modem messages through open gates

### ISSUE THREAD

**Issue by catalyticenzyme** [MrJake222/AUNIS#320]
In the TV show, radio signals can propagate through open gates in both directions, allowing communication, control of MALPs and UAVs, and opening of the iris. If wireless modem messages propagate through the gate, then you can do the same thing in-game, creating your own MALP or UAV out of OpenComputers drones and robots and perhaps creating your own shield/iris system using a tablet as a GDO.

**Comment by MrJake222** [comment]
They propagate. At least they should.

**Comment by catalyticenzyme** [comment]
I tested it and it works, thanks!
