### ISSUE TITLE
Crash when i use Dial home device or universal dialer

### ISSUE THREAD

**Issue by Chocodu31** [MrJake222/AUNIS#321]
Hello, i crash when i use dial home device on my server.

[Logs](https://hastebin.com/puzosageki.rb)

**Comment by slava110** [comment]
Hi. Thanks for reporting. Do you have same problem on latest alpha version of the mod too? You can download latest alpha from [Github Releases](https://github.com/MrJake222/AUNIS/releases)

**Comment by Chocodu31** [comment]
WOah that work THANKS MEN
