### ISSUE TITLE
Crash when interacting with pegasus gate

### ISSUE THREAD

**Issue by IronmanVeronika** [MrJake222/AUNIS#328]
[crash-2021-12-10_19.45.56-client.txt](https://github.com/MrJake222/AUNIS/files/7694983/crash-2021-12-10_19.45.56-client.txt)

**Comment by MrJake222** [comment]
This mod doesn't have pegasus gate. You're probably looking for aunis ressurection https://github.com/MineDragonCZ/Aunis1
