### ISSUE TITLE
my minecraft can't load the stargate horizon texture

### ISSUE THREAD

**Issue by Fraeric123** [MrJake222/AUNIS#329]
Hi, my minecraft can't load the stargate horizon texture. Please help me solve this problem! It spoils the look a lot! 
video:
https://vimeo.com/658176388/d10076179d

**Comment by MrJake222** [comment]
Your graphics card needs to have at least 2 GB of VRAM.

**Comment by Fraeric123** [comment]
My computer has:
Processor: Intel (R) Core (TM) i3-7020U CPU @ 2.30GHz 2.30 GHz
Installed RAM: 4.00 GB
System type: 64-bit operating system, processor for the x64 platform

**Comment by MrJake222** [comment]
But how much video RAM have you got? Check it with GPU-Z or something.

**Comment by Fraeric123** [comment]
I managed to run the texture of the Stargate horizon
video: 
New Recording - 18. 12. 2021 20:28:16](https://vimeo.com/658184604/e522ee8f7e
