### ISSUE TITLE
Transport Rings cause errors and don't play sounds when used on dedicated servers

### ISSUE THREAD

**Issue by PenguinBomber** [MrJake222/AUNIS#33]
[crash-2019-08-09_21.37.12-client.txt](https://github.com/MrJake222/AUNIS/files/3488487/crash-2019-08-09_21.37.12-client.txt)
Every time a transport ring has to play audio when the player is connected to a dedicated server, an error is thrown and no sound is heard

**Comment by RedstoneSucht** [comment]
We have the same problem. And we hear the stargate only by rotation, eventhorizont and deactivation
