### ISSUE TITLE
Can't dial back Orlin's gate

### ISSUE THREAD

**Issue by Erwan3289** [MrJake222/AUNIS#330]
Hey, I kinda have a problem: 
I'm running aunis on a server and crafted an orlin gate, went trough. Now I'm  stuck in the nether and can't dial back the Orlin gate, with and without the serpens caput glyph, added a dhd crystal. Nothing work. help

**Comment by MrJake222** [comment]
What address are you dialing? Console log?

**Comment by Erwan3289** [comment]
Dialing earth (7 chevrons since groups make it need only 7), but I had the last version of aunis, not aunis ressurection
