### ISSUE TITLE
Pegasus Incoming Wormhole Sound Bug

### ISSUE THREAD

**Issue by Onyx1128** [MrJake222/AUNIS#333]
Describe The Issue:
If a Pegasus gate is dialing and gets an incoming wormhole, the sound from it dialing does not go away.

Steps To Reproduce:
1. Use Pegasus gate to dial any gate in the world 
2. Use another gate to dial Pegasus gate before it activates.
3. Activate Stargate

**Comment by MrJake222** [comment]
This mod doesn't have pegasus gates, you're probably looking for aunis resurrection or sth like that
