### ISSUE TITLE
Incompatibility with Advanced Rocketry

### ISSUE THREAD

**Issue by ItsAslan** [MrJake222/AUNIS#334]
The stargates do not work when attempting transport to an advanced rocketry planet.

**Comment by MrJake222** [comment]
Any logs?

Btw this is unmaintained, check out Aunis Resurrection.

**Comment by ghost** [comment]
Where can I find the logs? Also, I just tested "Aunis Resurrection" and it does not work either.

**Comment by slava110** [comment]
What do you exactly mean by `does not work`? It doesn't open or what?
You can find latest logs in `.minecraft/logs` folder (`latest.log` and `debug.log`)

**Comment by ghost** [comment]
> What do you exactly mean by `does not work`? It doesn't open or what? You can find latest logs in `.minecraft/logs` folder (`latest.log` and `debug.log`)

Wasnt opening, however I went to their discord server and got everything sorted out
