### ISSUE TITLE
Remote control for the Transport Rings

### ISSUE THREAD

**Issue by PenguinBomber** [MrJake222/AUNIS#35]
Some form of item to control the rings, so you don't have to always have a ring control panel in the area

**Comment by MrJake222** [comment]
Been thinking about it... Like a Goa'uld glove. But I think it should have some limitations to it(at least for the first tier). Like connecting only to the nearest ones. And 2nd tier would need a Endstone for ex.

**Comment by DarthSidious666** [comment]
As another enhancement to the rings I would suggest using this panel design found here:
https://www.sgmod.de/index.php?page=manual, 

![](https://www.sgmod.de/images/manual/ringpanel_1_overview.jpg)
Shows the correct panel look and feel.

I'll keep trying to dig out a proper source picture, I'm sure in the SG1 series there was a close-up of one of them.

**Comment by MrJake222** [comment]
Isn't it exactly the same as we have in Aunis?

**Comment by DarthSidious666** [comment]
Not quite, the symbols on this one are more complex.
Maybe it's just a small aesthetic grip I have.

**Comment by MrJake222** [comment]
Okay this is solved now with Universe Dialer.
