### ISSUE TITLE
Bug: Ringtransporter 

### ISSUE THREAD

**Issue by RedstoneSucht** [MrJake222/AUNIS#38]

**Comment by RedstoneSucht** [comment]
When the Ring_Transporter dials each other at the same time, the blocks around the ring-transporter break it looks like that
![2019-09-20_22 30 42](https://user-images.githubusercontent.com/35812887/65357146-79002080-dbf6-11e9-8614-42850991d540.png)

**Comment by MR-Spagetty** [comment]
Why do you have them so close?
Yes they are designed for short range transportation but not that short range

**Comment by RedstoneSucht** [comment]
I put them so close, cause of the bug they have to be activated at the same time

**Comment by MrJake222** [comment]
I can't reproduce it..., maybe I fixed it along the way :thinking: Anyway, closing this now. If the bug persisit in 1.6, please open a new issue. Thanks.
