### ISSUE TITLE
Minor aesthetic with chevron

### ISSUE THREAD

**Issue by lieven121** [MrJake222/AUNIS#4]
The chevron that is active does have a different color but doesn't feel like its shining.
Maybe it's me or a slightly brighter color might do the trick.
![image](https://user-images.githubusercontent.com/7773244/60205331-36c27f80-9851-11e9-85c6-cf3dadfdb627.png)

P.S. I do like the actual light they emit :).

**Comment by lieven121** [comment]
It would also be nice if they actually move like the show.
(even this only happens if the gate is dialed manually, but this is the same for the spinning ring)

Don't know if you prefer that I open a second issue for this. For now, I leave it here

**Comment by MrJake222** [comment]
You turned _Check gate merge_ to false, don't you?

When there is a Chevron block right there, they emit light. At least they should. It is better visible when there're blocks around. Minecraft doesn't have a way to create a point light, sadly. And hacking .obj models into it is a little bit too much for it.

> It would also be nice if they actually move like the show.
> (even this only happens if the gate is dialed manually, but this is the same for the spinning ring)
In the show, when dialing from the DHD, only the final one moves. When dialing with the computer in SGC by manually spinning the ring into position, top one moves for each one, but only the top one(https://www.youtube.com/watch?v=KCBs80-PjC4). Every chevron moving is a movie thing(1994 original one) and SGCraft thing, which I absolutely hate ;)

Thank you for your feedback, whatsoever ;)

**Comment by lieven121** [comment]
Yes the gate had forming problems (was testing another issue)
But it still looks a bit bland (see image) could you maybe try increasing the contrast of the texture.
![image](https://user-images.githubusercontent.com/7773244/60206662-72127d80-9854-11e9-8f2f-a1b32b41d8d9.png)

I also noticed this minor aesthetic bug while observing them 
![image](https://user-images.githubusercontent.com/7773244/60206753-a2f2b280-9854-11e9-879e-33e8f3ea306a.png)

About the ring completely I was wrong indeed I was so used to other mods thx for correcting me.
But as you can see in your video the top chevron locks every time and lights up. It would be so cool if this gate did that too (maybe optional).

**Comment by MrJake222** [comment]
Yes, I plan on adding OpenComputers support, so you could build up your own SGC. And then, expected behavior would be as shown in the video.

I'm aware that the gate looks best at daytime and not so good at night. The whole model is rendered as one block(Base block to be exact) and I cannot separately lighten up parts of the model... Minecraft's engine is just too simple for that kind of lighting.

As regarding the last image, I'm no 3D master myself and Blender and my .obj renderer are sometimes working oddly. I tried to fix It but with no success, I may look into it once again.

**Comment by ShicKla** [comment]
@MrJake222 Would it be possible to have the invisible block that is located at/near the particular chevrons to emit a light level? I am unsure how the end result will look doing that, but it is just a thought.

**Comment by craft90** [comment]
I'm not 100% but I'd believe Optifine can make Minecraft visualize spotlights. At least someone had managed to do that in a texture pack for another Stargate Mod (Stargate Network). That said Optifine does have its issues. (Like breaking certain mod banners I noticed). Ofc I do not know of that can be added in and just require a soft dependency.

**Comment by MrJake222** [comment]
I've tried like everything with this model by now and it's still wrong. I don't have ideas by now xD
