### ISSUE TITLE
On a computer dial, if the final chevron can't lock, it should be stuck for a moment

### ISSUE THREAD

**Issue by Firecreeper240** [MrJake222/AUNIS#41]
The title is pretty self-explanatory. When dialing from Opencomputers and the final chevron can't lock, the chevron should be stuck in place for a moment. I will provide a screenshot as an example of what I mean.
https://imgur.com/a/AYBDJw8

**Comment by RedstoneSucht** [comment]
You mean like that?
![Anmerkung 2019-10-19 234833](https://user-images.githubusercontent.com/35812887/67155936-60c81200-f318-11e9-9742-f76938eca2d7.png)

**Comment by Firecreeper240** [comment]
Yeah

**Comment by dustojnikhummer** [comment]
There is a dialing program? Or is it just the one with a fixed preset address?

**Comment by RedstoneSucht** [comment]
That is SGCSim

**Comment by Firecreeper240** [comment]
This is what it should look like:
https://youtu.be/OXgqDYO31jc

**Comment by StargateMC** [comment]
@dustojnikhummer https://github.com/StargateMC/DiallingComputer

This is designed for 1.7.10, with the GDO functionality specifically to our 1.7 server, but with some tweaks it will work with Vanilla SGCraft.

We're about to update it to support 1.12.2.

**Comment by MrJake222** [comment]
@Firecreeper240 Where does that video come from? Do you have a version where the gate actually opens? Do you have the last(failing) sound file?

**Comment by Firecreeper240** [comment]
This video is from the game Stargate Network. As of right now, I don't have the sound file or a video of the the gate opening.

**Comment by Firecreeper240** [comment]
I put the file on Discord.

**Comment by MrJake222** [comment]
Fixed by https://github.com/MrJake222/AUNIS/commit/3f68ddf21ebb1424acdf6ef13af2d61f0f9cc40d
