### ISSUE TITLE
Bug: Ringtransporter

### ISSUE THREAD

**Issue by RedstoneSucht** [MrJake222/AUNIS#43]
Ringtransporter link each other only on horizontal 40m.
I send the config with.
[aunis.txt](https://github.com/MrJake222/AUNIS/files/3856230/aunis.txt)

**Comment by PoltixeTheDerg** [comment]
Are you trying to say there's a horizontal limit? If so this isn't a bug rather intended, rings are for vertical, not horizontal travel.

**Comment by MrJake222** [comment]
But the config provided says 100m limit

**Comment by RedstoneSucht** [comment]
I didn't say, that was on deciated server

**Comment by MrJake222** [comment]
Hmm, seems working fine for me. Did you change the _server_ config file?

**Comment by RedstoneSucht** [comment]
Yes. It was set to 100 m and works only on 40m

**Comment by MrJake222** [comment]
But the client file or the server file? I've just done it myself and it works, so maybe fixed it along the way...

**Comment by RedstoneSucht** [comment]
server file

**Comment by RedstoneSucht** [comment]
I suggest we close this issue. When this bug happens again, i will open a new one

**Comment by MrJake222** [comment]
Nice idea
