### ISSUE TITLE
OC networking support over open gates

### ISSUE THREAD

**Issue by PoltixeTheDerg** [MrJake222/AUNIS#48]
Add the ability to connect OC networks through an open Stargate

**Comment by MrJake222** [comment]
I thought about it, and maybe energy/fluid/items transportation

**Comment by StargateMC** [comment]
Probably best to just allow wireless OC through the gate, like greg ewing did with SGCraft.
As for items/energy etc, dont you already transport non player entities? :) Love your work by the way.

**Comment by MrJake222** [comment]
Greg actually retransmit OC messages on the other end. It would be a nice opportunity for a remote iris opener with remote terminals. By items I mean like a pipes/conduit way, not throwing them manually through. And thanks ;)
