### ISSUE TITLE
Mysterious pages dont do anything

### ISSUE THREAD

**Issue by uncoveredkhan09** [MrJake222/AUNIS#54]
Mysterious pages don't work anymore. I made one but when i try to use it nothing happens. I've got my gate all set up and was excited to use it for the first time in a pure survival world but I'd have to go and make a whole other one now :/

**Comment by MrJake222** [comment]
1.7 fixes that i believe

**Comment by MrJake222** [comment]
Check it with _1.7.1_ and report back please
