### ISSUE TITLE
An idea for how Universe gates should function

### ISSUE THREAD

**Issue by PoltixeTheDerg** [MrJake222/AUNIS#56]
Universe gates should by default work as Milkyway gates currently do, but if put on an Archimedes ship can be assigned a code for dialing into from anywhere using the 9th chevron.
While on an Archimedes ship the gate will change address every time the ship is re-formed, the code will never change though, once assigned the gate will have to be rebuilt to have its code changed.

**Comment by StargateMC** [comment]
You could use a similar approach to what i've just taken with our server's build of SGCraft:

https://pastebin.com/SU5ykF68

This allows for the coordinates of the gate to be updated independently to the address, while borrowing the idea from the SGDimensionMap class.
For my instance, I'm using the world name as the stargate address (we have 100k worlds so need to).

**Comment by MrJake222** [comment]
Aren't Archimedes ships stuck on 1.7.10?

**Comment by PoltixeTheDerg** [comment]
Closed due to universe gates being implemented
