### ISSUE TITLE
Orlin Gate on dedicated Server not working

### ISSUE THREAD

**Issue by RedstoneSucht** [MrJake222/AUNIS#63]
I know the Orlin Gate is not fin now. But we tried to setup an Orlin Gate, set an Destination and gived an redstone signal. the Orlin Gate is not dialing to the Destination gate

**Comment by MrJake222** [comment]
Thank you for pointing out Orlin's gate issue with dedicated server.

**Comment by MrJake222** [comment]
I rewrote rendering and server-side code, probably will release it with 1.8, because it's too big rewrite for me to be sure right away.
