### ISSUE TITLE
2 Major bugs discovered, one is more of an annoyance, the other bricks the world

### ISSUE THREAD

**Issue by Hyper-Tex** [MrJake222/AUNIS#64]
Okay, this first one doesn't generate a crash report but I found a consistent way of triggering it. First some explanation, I was testing around with the 1.7.0 and later versions of this mod. I was in creative mode, on a superflat world. I was using the mysterious page address, but just the first 6 symbols and then the point of origin on the DHD. But, I noticed that the wormhole shut down too fast, after about 20 seconds or so. So, I was testing to see if that was consistent, using creative mode to get fully charged master control crystals. However, **after replacing the crystal usually 2 or 3 times**, sometimes more, sometimes less, **when attempting to dial again, the game just gives up**, with no crash report. One time while doing this though, I was just kicked out of the world, not a crash. I forgot to screenshot it, but it was a fatal error screen, connection to server was terminated. I guess the game counts single player worlds as servers I guess?
My guess is it has **something to do with lighting updates**, a similar glitch happened when I was blowing up the gate with tnt in an older version of the mod. In fact, it's almost identical to it as you can rejoin the world again just fine, like nothing happened. So, while annoying, it's not too bad, hope you can find a way to fix it though. 

This second bug however is 100% bad as it can brick the world, a.k.a render it unplayable as it won't let you even enter the world once you trigger it. Thankfully, this bug does generate a crash report which I will paste below. So, when dialing the gate with the **DHD**. I found when pressing the big red button to activate it, **you can press it again quickly to shut it down too** (timing is kinda tight, but still. I **found the easiest way to recreate it would be to press the big red button the instant after you press the point of origin symbol**, and just keep right clicking (don't hold it down) the big red button), the problem is the gate **still activates while it's shutting down**. **the lights turn off, but the unstable vortex forms as well as the event horizon**. This is obviously causing a conflict in the code, resulting in a crash, and unfortunately reloging in does not help as with the other glitch, effectively rendering the world, at least in single player, useless. As I stated before, this is a real bad glitch. I have a crash report as well as a video showing this.
[crash-2020-02-18_03.47.02-server.txt](https://github.com/MrJake222/AUNIS/files/4218448/crash-2020-02-18_03.47.02-server.txt)
unfortunately I couldn't save the sound and it's a low quality gif file. I had to convert the file, but I still have the MP4s.
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/17879365/74717782-9a415900-51f6-11ea-81aa-0714d7da2dfb.gif)

**Comment by Hyper-Tex** [comment]
Okay, i caught that glitch where the game randomly crashes when you use the dhd, what I didn't realize it was a kick, not a crash, but it acts weird so the game usually just freezes. 
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/17879365/74722874-45561080-51ff-11ea-971a-32bb514066de.gif)

**Comment by MrJake222** [comment]
I've managed to fix the 2nd issue(closing-while-opening). But I think the first issue is related to you live-swapping the crystal, not the swap count.

**Comment by Hyper-Tex** [comment]
*nods* Well, I'm still not 100% sure what's causing the odd kick, not a programmer after all. But as I said, it's more annoyance than anything else. Still, if you can figure it out, it'd be nice. ^_^ The major thing was that second one. I'll keep testing when I can, seeing if I can break the thing more :P

**Comment by MrJake222** [comment]
I get it also, but like 1 in 10 mysterious pages I use... and I really don't know why this happen and testing 10 pages to find one case to replicate the issue ONCE per page only is annoying...

**Comment by Hyper-Tex** [comment]
It's not address by address I can tell you that. It seems to happen almost randomly, I will give you that certain ones seem to trigger it more than others, but I was using the same address multiple times when the kick in the gif happened. Also, you might not see it, but I'm replacing a completely dead crystal with a fresh one, don't know if that's a factor, but since the gif is so low quality, figured I'd let you know.

**Comment by MrJake222** [comment]
I might just lock the replacement when the gate is active and add a message, sth like "Don't mess with the DHD when the Stargate is active"

**Comment by Hyper-Tex** [comment]
But it wasn't active thought. I let the gate shut down before replacing it

**Comment by MrJake222** [comment]
Hm, I was testing it "live" but could you please try waiting a bit longer?

**Comment by Hyper-Tex** [comment]
I mean, sure, Now that it's known

**Comment by Hyper-Tex** [comment]
Okay, I found out another possibility. I dug through the regular log. I would post the whole thing here, but I don't wanna take the chance of it having something that could be used to hack me. Thanks for telling me to look at the regular logs by the way, as well as the game output console. So, I went through the same procedure, and I tested this on both the version I was using, and your latest one (still happens). So, I found out it's not the crystal replacing at all, it's something to do with when the gate closes, as an exception generates the moment is starts closing it does along with a bunch of other things at [00:57:31] in the log. I do replace the crystal as it's completely drained now.
Then in [00:57:34] in the log is the moment I press the first symbol on the dhd, this then of course, triggers the freeze.
[Gate kick log.txt](https://github.com/MrJake222/AUNIS/files/4223752/Gate.kick.log.txt)
What's not shown in that log is the final string of code. Let me paste it
00:58:46.147
Process crashed with exit code -805306369

Again, i can't read code, so I can only guess as to why. It could be lighting updates again. but the fact this generates the moment it starts to close (which also explains the randomness to me at least) might have something to do with how the receiving gate renders that area. Also, I never go through the gate. Could that be a factor?
Anyway, hope this helps

**Comment by MrJake222** [comment]
Hm, I thought I've fixed this one with the previous update, but I guess the fix somehow didn't make it to the final version... So I'll try push a new version to Curse. But this one is different from the one I've been testing on.

**Comment by Hyper-Tex** [comment]
Well, the major crash WAS fixed, the one where it closes while opening. I did test it. It's just this kick issue that's the problem now, the one shown in the second gif. All I can say is good luck. And I'll try to find more

**Comment by MrJake222** [comment]
I'm closing this one, test the new version and feel free to reopen or create a new one ;)
