### ISSUE TITLE
Stargate template rendered in world

### ISSUE THREAD

**Issue by MrJake222** [MrJake222/AUNIS#66]
I was wondering if when u place any stargate base block it shows a model of where to place the respective ring and chevron blocks to create the gate (would be dependent on the config "stargate size" option and type of gate).

https://mo.simeonradivoev.com/wp-content/uploads/2015/05/inactive-fusion-reactor-controller.png

> Originally from *Geocube101* from Discord

**Comment by Hyper-Tex** [comment]
Yes yes, and yes
