### ISSUE TITLE
game crash after crossing 7 gates in a short time.

### ISSUE THREAD

**Issue by HDL34** [MrJake222/AUNIS#69]
by continuing my tests, the game a finally crash after crossing 7 gates in a short time. After restarting the game, you cannot return to the map. It remains blocked indefinitely at the "loading of the ground".
![image](https://user-images.githubusercontent.com/61374058/75111701-37f4b800-563d-11ea-8f5e-65ba8b776dfe.png)

**Comment by MrJake222** [comment]
Post crash logs

**Comment by HDL34** [comment]
I no longer have the crash log. I will do it again hoping that it plants in the same place. to get the crash log.

**Comment by MrJake222** [comment]
You have all your logs in .minecraft/logs folder. You can try to search there.

**Comment by HDL34** [comment]
I have a crash reports folder generated for each game crash. Otherwise in the log folder, I don't know if that could help. 

It is the most recent that just at the time of the crash.
[crash-2020-02-24_10.34.02-server.txt](https://github.com/MrJake222/AUNIS/files/4243864/crash-2020-02-24_10.34.02-server.txt)

**Comment by HDL34** [comment]
I pushed my tests further and I noticed that it is my 7th door that is the problem. Because when you walk through the gate, the game hangs and the map it and becomes corrupt.
This is due to the update of the mod because with the 1.5.0 of the mod, I have no problem.

**Comment by MrJake222** [comment]
So you create 7 Stargates with Mysterious Page and come through them one by one? Or you create them by hand?

**Comment by HDL34** [comment]
I did one last test. Since version 1.5.0-beta-hotfix3.1, I put location marker near door 6 and then returned to my main base and quit the game to put the latest version of the mod and then start the game. Just looking in the direction of the location marker, the game to crash 5 seconds later. And the map becomes corrupt after restart.

**Comment by MrJake222** [comment]
Were the gate open? Crash log is different from the last one?

**Comment by HDL34** [comment]
Here is my last crash log.
[crash-2020-02-24_13.08.50-server.txt](https://github.com/MrJake222/AUNIS/files/4244543/crash-2020-02-24_13.08.50-server.txt)

**Comment by MrJake222** [comment]
You closed the gate before saving?

**Comment by HDL34** [comment]
All the doors were closed. And they are full of energy.

**Comment by MrJake222** [comment]
So it happens when you load the world from 1.5 into 1.7 with some closed Stargates?

**Comment by HDL34** [comment]
yes

**Comment by MrJake222** [comment]
Can you please upload the world somewhere? The working one from 1.5?

**Comment by HDL34** [comment]
I can provide you with my world but you will need all the other mods I use in it in the map

**Comment by HDL34** [comment]
or else I will provide you with my modpack.

**Comment by MrJake222** [comment]
And what happens if you load it without other mods? Maybe I'll need only Aunis?

**Comment by HDL34** [comment]
Without the other mods, a good part of my constructions disappears. And I also have an aunis door to the Moon with the Galacticraft mod.

**Comment by HDL34** [comment]
Which launcher do you use?
I use TLauncher. Convenient to make modpack

**Comment by HDL34** [comment]
I'll pass you both. My modpack and a folder with just the map and mods in case my modpack is incompatible with your Launcher.

**Comment by MrJake222** [comment]
I use official one

**Comment by HDL34** [comment]
ok. I hope that my modpack created with TLauncher will still work on the Official Launcher. In principle yes because TLauncher manages TLauncher accounts and Mojang accounts.

**Comment by HDL34** [comment]
The advantage of using my pack, and that you will have an easier time diagnosing the latest bugs by adding the latest version of the mod.

**Comment by HDL34** [comment]
https://www.transfernow.net/O7QZPx022020
The modpack is coming soon.

**Comment by MrJake222** [comment]
Whoa, that's a big world...

**Comment by HDL34** [comment]
https://www.transfernow.net/6vrVM1022020

**Comment by HDL34** [comment]
thank you 😀

**Comment by HDL34** [comment]
Just out of curiosity, what do you think of the redesigned textures of the mod?

**Comment by MrJake222** [comment]
The blocks don't fit very well imo :/

**Comment by HDL34** [comment]
ha

**Comment by HDL34** [comment]
Hi, have you tested the modpack? What would be the origin of the crash of the map with the door zone 6 after updating the mod?

**Comment by MrJake222** [comment]
No, I have school now, maybe on weekend.

**Comment by HDL34** [comment]
Ah OK. have a good school day. 😉

**Comment by MrJake222** [comment]
Thanks ;)

**Comment by HDL34** [comment]
I have a hypothesis concerning the crash of the game with version 1.7.5 of the mod. zone gate 6 has kept its old pattern. While the others have had their update. I had the idea to check with MCEdit.
![image](https://user-images.githubusercontent.com/61374058/75246530-3c9da580-57d0-11ea-9628-fe6dc7ca26b8.png)

**Comment by HDL34** [comment]
The desert village gate also has the old pattern. As well as the door of the End. And I also think that the Nether must be the same.

**Comment by MrJake222** [comment]
It changes when loaded, but the provided crash log has nothing to do with pattern... at least I think so

**Comment by HDL34** [comment]
good, after breaking the affected doors and going to the point located with the Stargate Network gate the game still crashes in the same place.

**Comment by HDL34** [comment]
Curious. While looking with MCEdit, I had broken a few blocks from the gate and after crossing the door of the StarGate Network mod and that the game crashed, I looked with MCEdit and I see that the door is reformed with the new pattern however.
![image](https://user-images.githubusercontent.com/61374058/75249478-b3d63800-57d6-11ea-876f-07bd7650cf31.png)

**Comment by HDL34** [comment]
Good, to go to the Nether, it works. From Nether to End it works too. But when I made the last symbol to go from the end to the moon, the game to crash.

**Comment by MrJake222** [comment]
It loaded and converted, but the issue is something in the base block. The gate is open, but it doesn't have it's dialed address set... :thinking:

**Comment by HDL34** [comment]
And after restarting the game, I saw that the card was completely corrupted with the blocks of the different mods installed. it made soup of all mods. all the blocks of the different mods have been mixed. To the point that it crashed again.

**Comment by HDL34** [comment]
ok, i will try that.

**Comment by HDL34** [comment]
I no longer have access to the moon. As well with Aunis 1.7.5 as with the Stargate Network mod. The game systematically crashes at the last symbol of the address.

**Comment by HDL34** [comment]
I am putting you all the crash reports of all my tests.
[crash-reports.zip](https://github.com/MrJake222/AUNIS/files/4250244/crash-reports.zip)
As well as debug logs.
[logs.zip](https://github.com/MrJake222/AUNIS/files/4250252/logs.zip)
So as soon as you have time, you can see where the problem is coming from.

**Comment by HDL34** [comment]
On a new map, going to the moon or another planet of the Galacticraft mod, I noticed that the Aunis mod was no longer compatible. Impossible to return to earth with the address of a door created before going to the moon. Ditto with the Porte d'Orlin. While this feature works with version 1.5.0.

**Comment by HDL34** [comment]
As much for me. Going from the earth to the moon it works. And like that it works now from the moon to the earth.

**Comment by HDL34** [comment]
Good, it works more. it only worked once.

**Comment by HDL34** [comment]
Hi. I just noticed when updating to the latest version of Galaticraft and its addons, the 1.7.5 from Aunis and perfectly 100% compatible this time. But of course, I do it from another ModPack that I created and on a new map to avoid the update bug on my usual map which I gave you a copy for the tests.

**Comment by MrJake222** [comment]
Reopen if you'll be able to reproduce it with upcoming 1.9.
