### ISSUE TITLE
Goa'ulds invasions

### ISSUE THREAD

**Issue by koravel** [MrJake222/AUNIS#70]
Hello there 0/
Just as idea - how about random goa'uld(or ori, replicators) invasions or/and some related things.
With this stuff, even in sp iris and energy shield would have some value.

**Comment by Hyper-Tex** [comment]
I made a similar idea in issue #36 3rd paragraph where they come through the gate

**Comment by koravel** [comment]
hmm, right. Suggestion duplicates 3rd idea from [https://github.com/MrJake222/AUNIS/issues/36](url)
