### ISSUE TITLE
Crash when deactivating gate with bright red button. mod version 1.7.5

### ISSUE THREAD

**Issue by Hyper-Tex** [MrJake222/AUNIS#71]
This crash might be related to issue #69 but triggered a different way. most of this is reposted from the discord server. 

"Oh boy, just found another rather big bug again, And this time it seems to corrupt the minecraft world you do this in. Not making it unplayable, but for sure doing odd things. I don't wanna push it in case it corrupts my game. the glitch is easy to pull off. It's in the 1.7.5 version of the mod. Just use a dhd to turn the gate on, then press the brb again to turn it off. this is not a simultaneous activation deactivation. just normal deactivation of the gate via DHD. My gosh if the DHD causing this many problems, I don't wanna think about the open computers testing I've yet to do! XD Oh crash report, gimme a sec."
(old crash report was posted here)

Tested on a superflat world. seed in game log

Game log: [Edited game log.txt](https://github.com/MrJake222/AUNIS/files/4259768/Edited.game.log.txt)
last line in the log was 'Process crashed exit code -1'
Crash report: [crash-2020-02-26_05.06.36-server.txt](https://github.com/MrJake222/AUNIS/files/4259769/crash-2020-02-26_05.06.36-server.txt)

Screenshot of gate setup:
![Screenshot (45)](https://user-images.githubusercontent.com/17879365/75417606-17f01d80-58f7-11ea-91ca-10d098b66916.png)

During attempts to recreate the glitch, it seemed to be trying it's best to hide, but I did find a way. Again, reposted from the discord.

"Okay, the reason it was never triggering was cause I never went through the gate in the times I was trying to recreate it. So, here's my final setup to trigger it. First, create a gate, (I don't think location matters but you can use the log entries and screenshots to find where i set up I used the same seed and location, down to the block placement) dial an address (I think it must be a mysterious page one) activate and go through the gate, let the gate shut down on it's own. / TP back to the gate's location, (don't TP into the gate blocks to where you have to break them, that seems to fix it, or at least makes it more difficult to trigger, and anyway, no one's gonna want to break and replace the gate every time) replace the drained crystal, dial, and then shut it down via the BRB. I did it about 10 times, on 2 occasions I had to activate and deactivate the gate after the TP step more than once to trigger it. But usually no more than 4 time"

**Comment by HDL34** [comment]
in my bug also I had either the map corrupted to the point of being unplayable or impossible to open it or else I had a soup with all the mods installed. Which was weird until the map crashed.

**Comment by Hyper-Tex** [comment]
Maybe I just got lucky? I did say my world starts acting odd when I rejoin, but it was never consistent, random blocks textures messing up, odd lines on screen, crashing when placing blocks. I wish I took screenshots. But then, sometimes, just nothing happens. I said it MIGHT be related since Jake said the crash reports looked the same.

**Comment by MrJake222** [comment]
You sure your computer is ok? No bad RAM or something?

**Comment by Hyper-Tex** [comment]
Yeah, we're good on that front

**Comment by Hyper-Tex** [comment]
I'm thinking the texture issue might be because it's an older version of it, block placement... not sure, that one was kinda rare though, might not have anything to do with this issue

**Comment by MrJake222** [comment]
You have logs from this playthroughs? Not crash oogs, normal ones?

**Comment by Hyper-Tex** [comment]
Unfortunately, I was testing so much, I lost track of which ones were which. The two logs I posted here I saved on my desktop to keep them separated And right now, I've got my main computer off.

**Comment by Hyper-Tex** [comment]
might explain why it's so inconsistent

**Comment by HDL34** [comment]
In the meantime, I'm staying on V1.5.0 for its good stability and it's almost total compatibility with Galacticraft.

**Comment by Hyper-Tex** [comment]
Btw, shouldn't you add the bug/crash tags to this?
Also, I think I know why the secondary bugs happened. Except for the core mods, a lot of the  thermal mods I was using weren't the latest versions, and since this mod uses the thermal series, the main bug might have caused the issues I was experiencing. I updated to the latest versions, the secondary bugs don't happen anymore, but the main one still does, and I get the same crash reports, line for line except for positions in the world, same goes for the game log, so the ones I posted here should work fine for your needs.

**Comment by HDL34** [comment]
Me, I have the latest version of thermal expansion since their release. So the bugs I have are always the same.
A bug that I observed that I forgot to say is the "DHD Control Crystal". On the latest version, when I put the crystal on, it disappears before I even press it again to push it into the gate. while on version 1.5, we can see the crystal placed on the door and we press a second time to push it in and have the 7th symbol.

**Comment by Hyper-Tex** [comment]
@HDL34 Hmmm, maybe yours is a separate bug then. Still since Jake said the crash reports looked the same, or at least similar, they might, and I'm gonna stress MIGHT, have some relation

**Comment by MrJake222** [comment]
Really old version now, If this bug persists in upcoming 1.9 please reopen.
