### ISSUE TITLE
Incoming wormholes doesnt reset dhd

### ISSUE THREAD

**Issue by uncoveredkhan09** [MrJake222/AUNIS#73]
So apparently if you start dialing out but someone dials in before you're done both sets of symbols show up on the dhd
![JPEG_20200307_085644](https://user-images.githubusercontent.com/60527794/76144926-db3cc880-6052-11ea-9f9c-6f2d7cff7f5b.jpg)

**Comment by RedstoneSucht** [comment]
I think this will be fixed, when the DHD doesnt show an incoming wormhole address

**Comment by RedstoneSucht** [comment]
I think, this bug is fixed. You can only see now your Symbols you put in
![2020-03-11_14 04 20](https://user-images.githubusercontent.com/35812887/76419827-5549b600-63a1-11ea-99e4-34367fc7fdb7.png)

**Comment by uncoveredkhan09** [comment]
I did this with the orlin gate, I know its now not as easy to test but that should be taken into consideration
