### ISSUE TITLE
Custom Addresses and/or Command To Give Note With Existing Gate Address?

### ISSUE THREAD

**Issue by brom10** [MrJake222/AUNIS#75]
So I know that /sgquery exists, but for a modpack it would be useful to be able to pre-generate a stargate in a specific place and then give the player the address at a certain point. Generating the stargates in custom structures can be done with other mods, but I can't seem to find a way to either set a custom address for the stargate, say with /blockdata, or a way to give a custom notebook page with the needed stargate address on it. I don't know how the addresses are generated if they're coordinate based or if they are just random, but I assume since /sgquery exists that there is just a list somewhere pairing addresses to coordinates?

**Comment by MrJake222** [comment]
I was thinking about adding something to set addresses :thinking: Command maybe.

Addresses are stored in a Map in WorldSavedData.

**Comment by MrJake222** [comment]
I'll be releasing new version soon, but I updated this page: https://github.com/MrJake222/AUNIS/wiki/Console-commands. Have a look.
