### ISSUE TITLE
Possibility of being updated for 1.15 with Fabric?

### ISSUE THREAD

**Issue by RowanSkie** [MrJake222/AUNIS#76]
Is there a possibility or an impossibility? Just asking. So far, out of the three Stargate mods I've seen, you have the best one possible.

**Comment by MrJake222** [comment]
Fabric? Why Fabric? I'm already familiar with forge and I'll probably stay with it. Updating is a goal someday but not now. If I ever leave 1.12 I want it to be finished, at least having Universe gates. And I'm heavily connected to Thermal Expansion machines and I think that mod is going to stay on 1.12 for a while...

**Comment by RowanSkie** [comment]
Alright. I just asked because I was running 1.15 with Fabric, and Forge for 1.15 is in Beta so... yeah.
