### ISSUE TITLE
Orlin's gate not opening

### ISSUE THREAD

**Issue by HDL34** [MrJake222/AUNIS#77]
Too bad we can no longer generate doors at random. But that's not the problem. The problem, impossible to activate the Orlin gate. Even put an Orlin gate in the Nether. 2nd problem: when I activate a stargate, and that I cross, the second closes more automatically. Obliged to go close the first manually.

**Comment by MrJake222** [comment]
Orlin gates are only functional to getting to the nether from overworld and getting back once and break default after 2 times.

**Comment by HDL34** [comment]
But even. After creating the Porte d'Orlin, and adding energy, I can no longer activate it.

**Comment by MrJake222** [comment]
What happens?

**Comment by HDL34** [comment]
The door starts but does not activate. And there is the new sound to indicate that it is not activated.

**Comment by HDL34** [comment]
I will make a video to show the problem

**Comment by MrJake222** [comment]
Didn't you dial it more than twice?

**Comment by HDL34** [comment]
If, because the first time, did not work and the second either. But you will see in the video.

**Comment by HDL34** [comment]
https://www.casimages.com/f/
https://www.casimages.com/f/

**Comment by HDL34** [comment]
https://www.transfernow.net/SyKajR032020

**Comment by HDL34** [comment]
The good thing about this new version, and the ghost blocks. So we see the shape to build. 😃

**Comment by MrJake222** [comment]
Firstly, try resetting config to defaults(particularly the Autoclose options and the power options). With Orlin's gate try to wait until the gate is fully charged and then try to dial it.

**Comment by HDL34** [comment]
I did not really understand with the "default configuration". For gate d'Orlin, I was quickly on the video but before, even with the gate fully loaded the same problem. And without beforehand trying to activate it for the first time while it is loading this one.

**Comment by MrJake222** [comment]
Remove .minecraft/config/aunis.cfg and restart the game

**Comment by HDL34** [comment]
ha ok

**Comment by HDL34** [comment]
Well I have to recreate the map because it crashes when generating the map.

**Comment by HDL34** [comment]
To be sure, I totally deleted the contents of the config folder.

**Comment by HDL34** [comment]
Now the stargate is working. But not yet the Orlin gate. But maybe we also need a door in nether. I'm testing this.

**Comment by HDL34** [comment]
no Don't work for Orlin gate

**Comment by MrJake222** [comment]
Can you provide me with a game log?

**Comment by HDL34** [comment]
Tomorrow I will provide you with a game journal 😉
