### ISSUE TITLE
More gate designs

### ISSUE THREAD

**Issue by uncoveredkhan09** [MrJake222/AUNIS#78]
I know you're planning for other gate types (universe and pegasus) which will have some kind of change between them but what about just more designs in general? Tollan and a reverse engineered human one have already been brought up but instead of making them work differently, use them as alternate "skins" to certain existing gates that can be applied

This could work with the new upgrade system you're going to use, have another slot for designs which will change the visual appearance

For example the milky way gate could use the human gate as one, pegasus could use the tollan's gate, etc

**Comment by uncoveredkhan09** [comment]
This could would also help if you planned on adding more alternate designs (like worn designs for each gate perhaps?) In the future as this system would already be implemented

**Comment by MrJake222** [comment]
I don't like the feeling of changing whole gate appearance with just one click... More likely you'll need to craft it from the beginning to be the Tollans' gate from the beginning. They were totally different from anything we saw in the show and changing it in CS: GO skins manner would be at least not realistic...

**Comment by uncoveredkhan09** [comment]
Well no, youd have to craft it still

But I was offering this up because it could help reduce the size of the mod a bit, by having less blocks and multi blocks youd have to form using said blocks it might help just a bit

**Comment by HDL34** [comment]
The mod is not that big.

**Comment by uncoveredkhan09** [comment]
Not right now but it's going to only get bigger, and if Jake adds 4 more highly detailed gates on top of everything else that's planned it could get big very fast

**Comment by MrJake222** [comment]
What's the problem of having 4x3=12 blocks?? You have JEI and search...

**Comment by MrJake222** [comment]
The Tollans are planned.
