### ISSUE TITLE
Game Crash on creation of Orlin Gate

### ISSUE THREAD

**Issue by djw8605** [MrJake222/AUNIS#79]
Running 1.8.0-beta.  Attached crash log.

Crash occurred after redstone powering the orlin gate and after some animation, but not portal, just some steam animation?  Crash occurs every time the game starts now as well, same spot.

[crash-2020-03-11_12.45.50-server.txt](https://github.com/MrJake222/AUNIS/files/4319896/crash-2020-03-11_12.45.50-server.txt)

**Comment by HDL34** [comment]
For my part, I have no crash but like you I have the animation of the vapor and then nothing.

**Comment by MrJake222** [comment]
What did you do? Are you dialing from Overworld?

**Comment by djw8605** [comment]
Yes, dialing from overworld.

**Comment by HDL34** [comment]
Same for me.

**Comment by MrJake222** [comment]
I see you have Advanced rocketry installed and I've heard it messes with the DimensionManager... Hmm, gonna check it out with AR installed :thinking:

**Comment by djw8605** [comment]
If it helps you debug, I downgraded to 1.7.5-beta.  This version doesn't have orlin's gate, but I can confirm that the regular stargate works within the same dimension (overworld).  I haven't tested across dimensions.

**Comment by MrJake222** [comment]
I'm pretty sure it has ;)

**Comment by MrJake222** [comment]
I am **not** able to replicate your bug with AR installed... Can you try to replicate it using minimum mods required?
