### ISSUE TITLE
Cast error - stargateminecraft from Curse

### ISSUE THREAD

**Issue by MrJake222** [MrJake222/AUNIS#8]
"I Crash when ever I attempt to create a gate I using the newest version as of the posting of this comment https://pastebin.com/dgqWXZ8D"

_Originally posted by stargateminecraft on CurseForge_

**Comment by craig1988** [comment]
This also happens to me everytime I try and build a gate

**Comment by MrJake222** [comment]
It's some wild Optifine trying to get light value from the wrong Block instance... It's reproducible with Optifine but not without it. Added simple check. Releasing fast bugfix soon ;)

**Comment by craig1988** [comment]
Thanks that would be great cause other wise I’m really enjoying the mod :-)
