### ISSUE TITLE
Game crash on 9th glyph dial

### ISSUE THREAD

**Issue by Agentx49** [MrJake222/AUNIS#80]
game crashes on dial of 9th glyph
[crash-2020-03-11_18.42.05-client.txt](https://github.com/MrJake222/AUNIS/files/4321708/crash-2020-03-11_18.42.05-client.txt)

**Comment by darkwolf-x2** [comment]
Also linked to this is that the gate and DHD won't reset until you break them/replace them or you can somehow dial successfully somewhere.

**Comment by PoltixeTheDerg** [comment]
in my testing seems to be related to #2 in some way, but crashes instead of letting you get more lit up

**Comment by HDL34** [comment]
ha, Another new bug. Well I will test on my side if I too have the same problem with 1.8.1.
Ha is I think I know why with 1.8.0 there was no way to use the Orlin gate. This is after you have deleted the random gate generation in the source code. And as on the Orlin gate there was no longer a way to tap it with an address parchment, it can no longer activate.

**Comment by MrJake222** [comment]
I didn't delete anything...

**Comment by HDL34** [comment]
Ha. well then, this is a bug. Because random generation no longer works. Version 1.8.1 does not correct for the Porte d'Orlin. And after several tries on the DHD, I had the bug of the first commentary as well as a crash of the game.

**Comment by MrJake222** [comment]
Mysterious pages work just well for me... And i don't know why you associate them with Orlin's

**Comment by HDL34** [comment]
previously you had to tap on it with the mysterious page to activate a destination.

**Comment by HDL34** [comment]
Ha and the bug of 1.8.1 that there is, when we are wrong on the glyph to engage. It is impossible resetting the DHD. Except by breaking the DHD and breaking the base block of the gate.

**Comment by HDL34** [comment]
Another small bug, a block breaks when dialing an address. As in the screenshot.
![image](https://user-images.githubusercontent.com/61374058/76502076-b033e980-6443-11ea-82a4-6ed153343cdb.png)

**Comment by MrJake222** [comment]
Now you cannot tap it with Page(but I'll probably restore that in config someday) it just gets linked to the nether ones.

The block breaking is 1.8 or 1.8.1?

**Comment by HDL34** [comment]
les 2 version

**Comment by HDL34** [comment]
Well at least in 1.8.1, the random generation of gates works again.

**Comment by HDL34** [comment]
Would it be possible to correct camouflage on non-vanilla blocks?
![image](https://user-images.githubusercontent.com/61374058/76504480-16227000-6448-11ea-8a32-6b4860947a2f.png)

**Comment by HDL34** [comment]
Here is a crash report if we make a random address. Unable to reset after. When you type 2 more symbols (10 in total), the game all simply crashes.
[crash-2020-03-12_10.27.51-client.txt](https://github.com/MrJake222/AUNIS/files/4323350/crash-2020-03-12_10.27.51-client.txt)
