### ISSUE TITLE
Suggestion of a new textures for adding the pegasus gate.

### ISSUE THREAD

**Issue by HDL34** [MrJake222/AUNIS#81]
Hi, I have a suggestion for new textures when the Pegasus gate will be added, I put in in link the new textures.
And suddenly, I changed the colors of the others to differentiate them.
![naquadah_block](https://user-images.githubusercontent.com/61374058/76605765-5568c380-6511-11ea-99b2-7fa4c751612c.png)
![naquadah_pegasus_block](https://user-images.githubusercontent.com/61374058/76605768-56015a00-6511-11ea-8446-4b47b4918163.png)
![stargate_milkyway_base_front](https://user-images.githubusercontent.com/61374058/76605769-56015a00-6511-11ea-9b2e-69d141f16a8e.png)
![stargate_milkyway_chevron_front](https://user-images.githubusercontent.com/61374058/76605771-56015a00-6511-11ea-881a-6c4d0c5b3846.png)
![stargate_milkyway_ring_front](https://user-images.githubusercontent.com/61374058/76605772-5699f080-6511-11ea-94b9-6726557e3a92.png)
![stargate_orlin_base_front](https://user-images.githubusercontent.com/61374058/76605775-5699f080-6511-11ea-992b-ebe29c97cc0d.png)
![stargate_orlin_member_block_front](https://user-images.githubusercontent.com/61374058/76605776-57328700-6511-11ea-9c0a-e72946382cf6.png)
![stargate_pegasus_base_front](https://user-images.githubusercontent.com/61374058/76605777-57328700-6511-11ea-8ed3-83027c303e86.png)
![stargate_pegasus_chevron_front](https://user-images.githubusercontent.com/61374058/76605778-57cb1d80-6511-11ea-8971-66a0a3e2ba7c.png)
![stargate_pegasus_ring_front](https://user-images.githubusercontent.com/61374058/76605779-57cb1d80-6511-11ea-85ac-80c69f0ecbe4.png)
![transportrings_block_bottom](https://user-images.githubusercontent.com/61374058/76605780-57cb1d80-6511-11ea-84c5-7183e1c17d7b.png)
![transportrings_block_top](https://user-images.githubusercontent.com/61374058/76605781-5863b400-6511-11ea-8b55-4267b422e51a.png)

**Comment by HDL34** [comment]
The other links are coming
https://nsa40.casimages.com/img/2020/03/12/200312030312955991.png
https://nsa40.casimages.com/img/2020/03/12/200312030313208179.png
https://nsa40.casimages.com/img/2020/03/12/200312030313493386.png
https://nsa40.casimages.com/img/2020/03/12/200312030313790269.png
https://nsa40.casimages.com/img/2020/03/12/200312030313937211.png
https://nsa40.casimages.com/img/2020/03/12/200312030314194251.png
https://nsa40.casimages.com/img/2020/03/12/200312030314448740.png
https://nsa40.casimages.com/img/2020/03/12/200312030314703981.png
https://nsa40.casimages.com/img/2020/03/12/200312030314957076.png
https://nsa40.casimages.com/img/2020/03/12/200312030315215390.png
https://nsa40.casimages.com/img/2020/03/12/200312030315464627.png

**Comment by MrJake222** [comment]
Wow, actually they're pretty nice ^_^ But what would you call the "blue stone" from the Atlantis ones? It's technically still Naquadah...

**Comment by HDL34** [comment]
I haven't thought about this details yet. But I think the name should appear in the Stargate Network mod because there is also the Pegasus gate.

**Comment by HDL34** [comment]
in the Stargate Network mod, there is the "sgcorecrystal" A perfectly blue crystal and the "pegasus upgrade" a slightly lightblue cian crystal.

**Comment by HDL34** [comment]
After as always, for my personal use, I me make an HD texture asset. 128x128.
I may be able to offer it to you later if you want.

**Comment by MrJake222** [comment]
Okay so I used my own textures already, but thank you for the suggestions. They actually inspired me.
