### ISSUE TITLE
Yet another DHD issue XD mod version 1.8.1

### ISSUE THREAD

**Issue by Hyper-Tex** [MrJake222/AUNIS#83]
Okay, I must must be cursed with finding DHD glitches, this one's really easy to trigger, i don't even think I need to give you the crash report for this one, it's that easy. I'll of course post it upon request.
So, what happens is, when you fail to dial an address or press the big red button in to middle of dialing (say you pressed the wrong symbol, and need to reset the gate) the symbols stay lit, as well as the chevrons. At first I thought it was just a visual bug, but when dialing again, the game crashes.
I will say that very rarely, when dialing the same symbols, the game won't crash. But I only had that happen once after 20 tests, so I think that was pure luck

**Comment by MrJake222** [comment]
Shit I forgot to put 1.8.2 on Curse that fixes this particular problem xD

**Comment by HDL34** [comment]
I had published a report on this bug.

**Comment by Hyper-Tex** [comment]
@MrJake222 Whoops. Oh well XD
And @HDL34 I didn't see it, Jake likely closed the issue before I could see it. Oh well.

**Comment by MrJake222** [comment]
I closed it by a commit, and was uploading 1.8.2 but Curse needs you to click "Save" button after upload and I forgot about it, uploading now. Please test it and report back.
