### ISSUE TITLE
Blocks missing in the generation of a new gate.

### ISSUE THREAD

**Issue by HDL34** [MrJake222/AUNIS#84]
![image](https://user-images.githubusercontent.com/61374058/76677660-519c7600-65d1-11ea-8095-b901f05da84d.png)
Version mod 1.8.3
If not for the DHD, it is good more problem.
Not missing blocks always happen. So, it's OK. This minor bug is not really important.
![image](https://user-images.githubusercontent.com/61374058/76678211-3122ea80-65d6-11ea-9c6a-e4f9f0549474.png)

**Comment by HDL34** [comment]
Hmm there is a small problem between Aunis mod and the appliedenergistics2 mod. On a new generation of gate, the gate is not generate but instead I have a big meteorite coming from the mod appliedenergistics2 lol.
![image](https://user-images.githubusercontent.com/61374058/76678086-3fbcd200-65d5-11ea-8ee3-211c604fe57d.png)

**Comment by MrJake222** [comment]
That is because world decorators run after I add the Gate to the world... and I don't know how to fix it :/

**Comment by HDL34** [comment]
After good it's not serious but better not be in survival mode lol. Otherwise we get burnt by lava. 😂
