### ISSUE TITLE
The Orlin Gate still refuses to activate.

### ISSUE THREAD

**Issue by HDL34** [MrJake222/AUNIS#85]
I don't know what he might miss. I put infinite energy, I put redstone and a lever to activate. But still does not work.

See bug video:
https://www.transfernow.net/ogb68s032020

**Comment by MrJake222** [comment]
Try increasing the power capacity of Orlin's gate in config. Esc, Mod options, Aunis, config, power options, Orlin's gate max power bor something like that.

**Comment by HDL34** [comment]
what value should i change and the quantity?
![image](https://user-images.githubusercontent.com/61374058/76701535-64db3e80-66c2-11ea-8700-3d85f753bf64.png)

**Comment by MrJake222** [comment]
Try setting "Orlin's gate internal buffer size" to dunno, 20 000 000 maybe :thinking:

**Comment by HDL34** [comment]
okay. I'm going to try

**Comment by HDL34** [comment]
no. Don't work

**Comment by MrJake222** [comment]
Reload world and replace Orlin's base block

**Comment by engineeringuofi** [comment]
It takes a long time to do...but it will activate in about 30-45 seconds
