### ISSUE TITLE
Bug with openComputer

### ISSUE THREAD

**Issue by HDL34** [MrJake222/AUNIS#87]
On my main map, I want to activate stargate from the moon to overworld with openComputer. But there is a problem. It always stops at the launch of the 4th rafters. And this bug and only by activating from opencomputer.
![image](https://user-images.githubusercontent.com/61374058/76683551-4ebb7880-6605-11ea-990f-ca804a3ea878.png)
![image](https://user-images.githubusercontent.com/61374058/76683561-62ff7580-6605-11ea-971e-1425b6a2dc0f.png)
I am on version 1.8.3 of the mod. I have upgraded since 1.5.0 host fix 3.
And on the old version, I didn't have this problem.
But going from the moon to Mars, it works very well.
And from the overworld to the moon, it hangs at the 6th chevron.
I also notice that the ring is no longer as fluid as before. There are lag. And yet I have a very good 32 GB ram machine and an RTX 2080.
See the bug video: https://www.transfernow.net/BydjoD032020

**Comment by HDL34** [comment]
But going from the moon to Mars, it works very well.

**Comment by RedstoneSucht** [comment]
Hey, try this -> Bootes

**Comment by HDL34** [comment]
What's this Bootes‎?
However, I fixed my problem with version 1.7.5 last time. I emptied the config folder to regenerate it and it works like clockwork. No more crash bug.

**Comment by HDL34** [comment]
I spoke a little too quickly. From the earth to the moon, no problem with opencomputer compared to version 1.8.3. But from the moon to the earth, with opencomputer it hangs in exactly the same place.

**Comment by HDL34** [comment]
by testing on a new map, the ring of 1.8.3 and perfectly fluid but it still blocks on the 5th rafter with opencomputer.
![image](https://user-images.githubusercontent.com/61374058/76701500-01511100-66c2-11ea-8a3e-6fad1a3f1ba3.png)
![image](https://user-images.githubusercontent.com/61374058/76701510-15950e00-66c2-11ea-8340-80791c5fb66b.png)

**Comment by MrJake222** [comment]
Change Boötes glyph to Bootes...

**Comment by HDL34** [comment]
Ah OK. I have understand now 😅

**Comment by HDL34** [comment]
I'm going to test to see if that's the problem

**Comment by HDL34** [comment]
Ha it works now 😃. But it will be necessary to modify this name there in the source code then.
