### ISSUE TITLE
re-dialing fail with opencomputer

### ISSUE THREAD

**Issue by HDL34** [MrJake222/AUNIS#88]
Re. I spoke a little too quickly earlier when I said that it worked. Because I had tested an address generated on another map and although the whole sequence is done, the door is not activated. But I hadn't tested with a mysterious new page. There I retested with a new Mysterious page with the famous "Boötes" and by writing it "Bootes" in the code to opencomputer, the sequencing is done entirely but it ends on a fail dialing when it activates the chevron point of origin.
So I conclude that there is a problem with the word "Boötes".
Because with the others, I have no problem. But I will goes tested with others.

**Comment by MrJake222** [comment]
You sure the address is correct and you have enough energy. Post. Your. Logs.

**Comment by HDL34** [comment]
yes because after I tried with another address without the "Boötes" and it works.

**Comment by MrJake222** [comment]
Post log, there should be info about how much energy Stargate needs. You have full buffer?

**Comment by HDL34** [comment]
Normally yes because I have not deleted anything yet.

**Comment by HDL34** [comment]
[debug.log](https://github.com/MrJake222/AUNIS/files/4334458/debug.log)

**Comment by HDL34** [comment]
Little question: did you test the latest version on my map that I gave you the last time?

**Comment by HDL34** [comment]
You will see that there is a freese when the ring is engaged. But freese disappears on a new generated map.

**Comment by HDL34** [comment]
I confirm that it is the "Boötes" that is the problem. On the 6th mysterious page generated, I have it in the last position and precisely that is where it stops.
![2020-03-15_17 14 55](https://user-images.githubusercontent.com/61374058/76705499-b98db200-66e0-11ea-9a6b-f9321f2a7939.png)
![image](https://user-images.githubusercontent.com/61374058/76705515-d1fdcc80-66e0-11ea-8006-3d96da755d66.png)

**Comment by HDL34** [comment]
And on 6 mysterious generated pages, the two with the symbol "Boötes" prevents from activating the door from openComputer.

**Comment by HDL34** [comment]
strange. it works when in the address the symbol "Boötes" is in the last position and I write "Bootes". But if it is in 2 nd or in the middle of the address, it does not work.

**Comment by HDL34** [comment]
I tested at least 7 addresses and it is the two with the symbol "Boötes" that there is a problem. apart from when it is in the last position it works.

So bug fix and that of the Porte d'Orlin and it will be good.
