### ISSUE TITLE
Allow Notebook Pages To Display In Item Frames Like Maps

### ISSUE THREAD

**Issue by brom10** [MrJake222/AUNIS#89]
Just had a thought, if we could place our notebook pages with addresses in itemframes and actually be able to see them just like how maps work, that would be nice so we don't have to sort through a bunch of addresses in our inventory

**Comment by MrJake222** [comment]
I'm planning of reworking Notebook pages and to finally add a **Notebook** itself. Maybe I'll also add this. It was brought on Discord before, but thank you for reminding me ;)

**Comment by HDL34** [comment]
You have a discord server?

**Comment by HDL34** [comment]
I really like this camouflage on the door when it spawns in the middle of the desert 😃.
![Annotation 2020-03-15 165742](https://user-images.githubusercontent.com/61374058/76740111-9f4de580-676d-11ea-8326-0288d08fd7f0.jpg)

**Comment by MrJake222** [comment]
There's is a link to Discord on Cruse....

**Comment by HDL34** [comment]
ok
