### ISSUE TITLE
Can't walk through gate/gate won't close

### ISSUE THREAD

**Issue by engineeringuofi** [MrJake222/AUNIS#9]
I dialed the gate, opened it, and couldn't walk through. I tried to disconnect and nothing happened. (I even tried breaking the dhd and stargate.

**Comment by MrJake222** [comment]
Any steps to reproduce? It could be anything at this point...

Breaking and replacing the Stargate Base block should fix the issue(stop the sounds and so on) but it will regenerate the address. Also relinking the DHD could be necessary(break & replace).

**Comment by engineeringuofi** [comment]
Breaking the base block destroyed the whole gate, but yes, it did work. I have a picture if it helps (you can kinda see that's it's active, but it is active.

https://photos.app.goo.gl/ZjcDs9id71cBuxEF7

**Comment by engineeringuofi** [comment]
It is on a MacBook, so that is probably the problem. MacBooks suuccckk to run mods on

**Comment by MrJake222** [comment]
Maybe a server lag or something... I'll close this one. When you get a reproducible case or maybe you get some errors on the console, feel free to open a new issue.

**Comment by Firecreeper240** [comment]
Dialing a Stargate to itself can cause this issue.

**Comment by engineeringuofi** [comment]
Maybe I accidentally dialed the same Stargate without noticing?

**Comment by MrJake222** [comment]
Quite possble. Related to #11.
